### ISSUE TITLE
how to pass params when use bootstrap3-dialog to show remote page

### ISSUE THREAD

**Issue by whogy** [nakupanda/bootstrap3-dialog#104]
i wanna bootstrap3-dialog to show a remote page, and i wanna to pass some params to the remote page.

the params is a little large, so i do not want to send the params via query string.

is there any interface i can use?

thanks indeed

**Comment by himel-ceps** [comment]
php framework: codeIgniter
javascript framework: jquery
css framework: bootstrap

Please, see this situation. I wanna open the dialog with a dynamic edit form of a product. One field of this form need to implemented datetimepicker. I loaded the form in message body and try to datetimepicker initiate on "onshown" event. But sometimes ajax response back before onshown sometimes after onshown. So when my server responses little bit slowly, datepicker doesn't work. 

my_dialog = BootstrapDialog.show( {
    title: 'Edit Product',
    message: $('<div></div>').load('product/edit_form',{ product_id: 2 }),
    onshown: function(dialog) {
          $('selector').datetimepicker();
      }
 });

Here, I bypass my aim by using like this:

my_dialog = BootstrapDialog.show( {
    title: 'Edit Product',
    message: $('<div></div>').load(
         'product/edit_form',
         { product_id: 2 },
         function($('selector').datetimepicker())
    )
});

But I think its an issue. Until ajax response reaches back, the dialog should not open.

**Comment by nakupanda** [comment]
Hi,

You did it in a good and right way in the second code snippet.

For flexibility reason, it's good to keep bootstrap dialog out of any ajax tricks, you can see even for Bootstrap Modal, the 'option' is being deprecated.

Thanks for you idea.

**Comment by himel-ceps** [comment]
Hi

Thanks for your information and help. Its great plugin !!! 100% of my
requirement is served by this plugin. Its more than what I was actually
searching in google !!! If I keep bootstrap dialog out of ajax then whats
the way to load a dynamic form on modal-dialog ?

Thanks in advance.

**Comment by nakupanda** [comment]
Hi,

By that I meant we shouldn't make any built-in ajax features for bootstrap dialog, use $.load, $.ajax or others to load remote data into it. This provides more flexibility and makes using different libraries together possible.

**Comment by himel-ceps** [comment]
Oh I get that now, Thank you.
