### ISSUE TITLE
Sychronous call  like window.alert or window.confirm

### ISSUE THREAD

**Issue by GauravAshara** [nakupanda/bootstrap3-dialog#107]
Hello,

You build really nice dialog boxes. Actually i want prompted dialog box until its take input from user it does run any other function sychronously.

function Dailog()
{
	 var defer = $.Deferred(); 
	var selectedFile="";
	var selectedFolder="";
	
	var data=BootstrapDialog.show({
      title: 'Save Pin File',
      message: function(dialog) {
          var $message = $('<div id="container_id" class="JqueryContainer"></div><div>File Name : <input type="text" name="fileInput" class="form-control" id="fileInput"  value="" /></div>');
			    return $message;
			},	            
			draggable: true,
			onshown: function(dialogRef)
			{
					
	},
      buttons: [{
      	id: 'btn-save',
        label: 'Save',
        cssClass: 'btn-primary',
        action: function(dialogItself){
        	
        	defer.resolve($("#fileInput").val()); 
        	dialogItself.close();
            
        	},
				cssClass: 'btn-default'
				}, 
				{
          label: 'Close',
          action: function(dialogItself){
          defer.resolve(null); 
              dialogItself.close();
					},
          cssClass: 'btn-danger'
      	}]
		});
		 return defer.promise();
}
function saveFileDailog()
{
	var temp="";
	
	Dailog().then(function (answer) {//then will run if Yes or No is clicked
              temp=answer;

            });
	 
          alert("Hello :" +temp);
	
	return temp;
}

In above code saveFileDailog() called it was return value first until user give his/her input.

Please help me for solution.

Thanks & Regards 
Gaurav Ashara

**Comment by cmwelsh** [comment]
It is impossible. You can't synchronously block for input without using `window.alert`, `window.confirm`, or. `window.prompt`. You should put the code inside your `then` method:

    dialog().then(function () {
        // put code here
    });

**Comment by GauravAshara** [comment]
Thanks its work for me.

**Comment by cmwelsh** [comment]
Cool. You can close this issue if your problem is resolved.
