### ISSUE TITLE
access to dialogs collection

### ISSUE THREAD

**Issue by ronan-paul** [nakupanda/bootstrap3-dialog#109]
Hello,

I handle several dialogs at the same time and I wish to access to the dialogs collection. 
My need are:
1 - define the id of a modal dialog 
I found a way to do this with dialogInstance.setId() method
=> Could I introduce a problem here ?
2 - direct access to dialogInstance with a native function 
for example: BootstrapDialog.getDialog( id )
=> I miss this feature
3 - browser the dialog collection with a native function
=> I think there is a function returning an array in the source code but I could not find how to call it.

For now, I could find an anwser by using this code:
		    	 $.each(BootstrapDialog.dialogs, function(id, dialogInstance) 
    			 {
		    		 if (dialogInstance.isRealized() && dialogInstance.isOpened() && dialogInstance.getId() == 'WHATEVER I AM LOOKING FOR' ) 
		    		 {
		    			 //do something with dialogInstance variable: 
		    			 my_function( dialogInstance);
		    		 }
    			 });

Thank you for your help

**Comment by nakupanda** [comment]
Hi Paul,

For 2), I think it makes sense, will add such a function later.

**Comment by waspinator** [comment]
just checking, is there a way to directly access a dialogInstance yet?

**Comment by nakupanda** [comment]
I believe you can do it by this way now

````
/** Assuming you know the dialog's id you are looking for**/
var dialog = BootstrapDialog.getDialog('1234567');
dialog.close();
````

See changes here https://github.com/nakupanda/bootstrap3-dialog/commit/176ce7d89147dab825223a194faa8dbc6ef65ad4#diff-415d7fbb86e89a18afa54b718bbf6345R266
