### ISSUE TITLE
ie8 error - Constructor undefined

### ISSUE THREAD

**Issue by MatneX** [nakupanda/bootstrap3-dialog#115]
Line41:
var Modal = $.fn.modal.Constructor;

ie8 says that Constructor of type undefined can't be called

**Comment by MatneX** [comment]
Ok, there is no problem.
Your script was loading faster than bootstrap.js. Changed the listener and now it works.

**Comment by nakupanda** [comment]
Good to hear that :)

**Comment by gullij** [comment]
I'm having that same problem now on Chrome 40.0.2214.115 (64-bit) on Linux.
How would I go about fixing this?
(Bootstrap 3.0.0)

**Comment by nakupanda** [comment]
Sounds like your bootstrap is too old?

Anyway I will take a look at it and give you feedback later
