### ISSUE TITLE
How to change this string by config?

### ISSUE THREAD

**Issue by mihdan** [nakupanda/bootstrap3-dialog#117]
https://github.com/nakupanda/bootstrap3-dialog/blob/master/src/js/bootstrap-dialog.js#L1175

**Comment by nakupanda** [comment]
My bad, I'm sorry, you can not change this for now. 

Allow me to implement it in next mirror version update.

**Comment by davidgjm** [comment]
Hi nakupanda,
Your library is great. It's exactly what I need for my application. Thank you for the good work!
I've the same request about the hard coded strings. I'm trying to use your library for non-English application. It would be great if you can extract the labels into separate js/json files for i18n support.
I can offer translation for Chinese.

BTW, I found it's doable to overwrite a few of your dialog titles to use my own translations. For example,
/**
 * BootstrapDialog translation messages
 */
BootstrapDialog.DEFAULT_TEXTS = {
    OK: '确认',
    CANCEL: '取消'
};
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_DEFAULT] = '信息';
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_INFO] = '信息';
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_PRIMARY] = '信息';
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_SUCCESS] = '成功';
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_WARNING] = '警告';
BootstrapDialog.DEFAULT_TEXTS[BootstrapDialog.TYPE_DANGER] = '错误';

**Comment by nakupanda** [comment]
HI @mihdan ,

Please see http://nakupanda.github.io/bootstrap3-dialog/#advanced-confirm-window

Hi @davidgjm ,

Please see http://nakupanda.github.io/bootstrap3-dialog/#i18n-message

For now please download https://github.com/nakupanda/bootstrap3-dialog/archive/master.zip to achieve improvements, the will be included in a new release later.

Thank you very much for using the plugin and giving feedback.

**Comment by mihdan** [comment]
Thank you very much

**Comment by davidgjm** [comment]
Thank you for the great work. The new version now works like a charm :)

**Comment by nakupanda** [comment]
My pleasure to help :)
