### ISSUE TITLE
Show spinner while remote page is loading

### ISSUE THREAD

**Issue by jqueryhacker** [nakupanda/bootstrap3-dialog#119]
I am loading a php page using the remote page (2) option. The page can sometimes take several seconds to assemble the required data so I would like to show a spinner or a "please wait" message.

Is there a way to do this?

Thanks for a great plugin.

**Comment by nakupanda** [comment]
Please try

```BootstrapDialog.show({
            message: function(dialog) {
                var $message = $('<div><spinner icon> Please wait..</div>');
                var pageToLoad = dialog.getData('pageToLoad');
                $message.load(pageToLoad);
        
                return $message;
            },
            data: {
                'pageToLoad': 'remote.html'
            }
        });
```

The only new thing is the message indicating loading status in $message.

**Comment by jqueryhacker** [comment]
Wow! That was fast.... works beautifully.

Thank you.

**Comment by nakupanda** [comment]
My pleasure to help :)
