### ISSUE TITLE
Change label button on click

### ISSUE THREAD

**Issue by Xarkam** [nakupanda/bootstrap3-dialog#120]
Hi,

howto change a dialog button label ?
Example, on click to 'Modify' button I want to change text to 'Save'

Thanks.

**Comment by nakupanda** [comment]
Hi,

For those buttons you're going create, you can specify labels this way:
````
BootstrapDialog.show({
     buttons:[{
          label: 'Your custom label'
    }]
});
````

And for those have been created, you can modify them this way:
````
 BootstrapDialog.show({
            title: 'Changing button label',
            buttons: [{
                label: 'Button 1',
                action: function(dialog) {
                       dialog.getButton('btn-2').text('New label');
                }
            }, {
                id: 'btn-2',
                label: 'Button 2'
            }]
        });
````

In short, if you had specified a 'id' for a button, later you can get it by dialog.getButton('the id'), ortherwise you might have to use something like 'dialog.getModal().find(YouButtonSelector)'.


Hope this helps.

**Comment by Xarkam** [comment]
Thanks, I test in next days :)

**Comment by Xarkam** [comment]
Thanks, it's okay :)
