### ISSUE TITLE
The close() function will "destroy" the dialog instance in cases where the dialog remains visible.

### ISSUE THREAD

**Issue by williamb1024** [nakupanda/bootstrap3-dialog#121]
If the `onhide` function returns `false` to prevent the modal dialog from closing, the `close()` function will still remove the dialog instance from the internal array of open dialogs and set the dialog's opened state to `false`.

This occurs with any of the available methods for closing the dialog, because ultimately all of the methods lead to a call to `close()`. 

The dialog instance should remain in an opened state until it is actually removed from the display.

**Comment by nakupanda** [comment]
Hi,

Is this a suggestion or a bug report ? As I don't remember there is a way stopping closing the dialog by returning false in onhide callback.

If this is a suggestion, I'd like to take a shot at it, it sounds cool.

**Comment by williamb1024** [comment]
Bug report. Using onhide to cancel closing of the dialog is demonstrated on the examples page in "Stop closing your dialog".

Looking at the code a bit more, it also appears that a non-autodestroyed dialog will never be removed from the internal dialogs list, which it should be when it closes ..

**Comment by williamb1024** [comment]
If you are willing to access the `bs.modal` data associated with the bootstrap modal dialog, the field `isShown` will be `false` after modal('hide') if the dialog is actually going to be hidden.

**Comment by nakupanda** [comment]
Thank you, I will take a look at it and try to fix it.

**Comment by nakupanda** [comment]
Thank you very much, @williamb1024 , I can't believe I made such a mistake.
