### ISSUE TITLE
Fix for #121 breaks #102

### ISSUE THREAD

**Issue by williamb1024** [nakupanda/bootstrap3-dialog#123]
The changes you made to correct #121 breaks the fix for #102.

**Comment by williamb1024** [comment]
Also, the fix for #121 is not complete .. the `close()` method still calls `setOpened()` changing the opened state to `false` even if the dialog doesn't actually close.

**Comment by nakupanda** [comment]
Sorry becoming lazy, I will read my code (and yours) more carefully and make a better fix soon.

Really appreciate you pointing out those details.

**Comment by nakupanda** [comment]
Hi William,

Please see https://github.com/nakupanda/bootstrap3-dialog/commit/99cb69b22cd414808910bf89e1ababe5d73021fc

**Comment by nakupanda** [comment]
William, perhaps due to the merge process I used

Pull your changes -> merge one of the commit into master -> Push changes

I didn't see you on the contributor list of this small plugin, I'm sorry for that.

**Comment by williamb1024** [comment]
I'll cancel the pull request, your code changes should resolve the issue. You left an `alert()` call in the `show.bs.modal` handler.

**Comment by nakupanda** [comment]
Yes, I noticed and removed it already.

**Comment by williamb1024** [comment]
Seems to be in working order.
