### ISSUE TITLE
updateButtons does not show footer in certain cases

### ISSUE THREAD

**Issue by williamb1024** [nakupanda/bootstrap3-dialog#125]
`updateButtons` method does not show the modal footer if a previous call to `updateButtons` caused the footer to be hidden.

If a dialog is realized with no buttons, a future call to `setButtons` will add the DOM elements, but not remove the `display:none` style from the modal footer. Adding a call to `show` before `find` in the `else` clause of `updateButtons` will resolve the problem.

    this.getModalFooter().show().find('.' + this.getNamespace('footer')).html('').append(this.createFooterButtons());

As a side note, calling `setButtons` with an empty button array will leave any existing buttons in the footer as DOM elements. It probably should remove the existing DOM elements.

**Comment by nakupanda** [comment]
Hi,

You're right, changes has been applied.

Please see here for a simple test http://jsfiddle.net/m9x0zg6L/

Thank you very much :)

**Comment by nakupanda** [comment]
By the way, as updateButtons() will cause wiping all existing buttons in footer, calling updateButtons() after addButton(...) may not work as expected in some cases, for example, if any event had been bound to those buttons, they will be lost after calling updateButtons().
