### ISSUE TITLE
Cannot read property 'Constructor' of undefined

### ISSUE THREAD

**Issue by gullij** [nakupanda/bootstrap3-dialog#128]
I'm getting the same error as discussed in this: https://github.com/nakupanda/bootstrap3-dialog/issues/115

I'm not sure which listener to change to fix this but surely the suggested fix points to a race condition in bootstrap-dialog?

**Comment by nakupanda** [comment]
Hi,

It will be helpful to create an example that reproduces the issue, for example, put your example.html, bootstrap lib and bootstrap dialog lib in a directory, package it in .zip or .tar.gz, e.g. then send it to javanoob@hotmail.com

Before getting your example.zip, I will take a look at the issue my way first.

**Comment by gullij** [comment]
I'll try to recreate this in a stand-alone package.

**Comment by anothrNick** [comment]
Make sure you are including the bootstrap js before this bootstrap dialog js, as it extends the bootstrap modal.

**Comment by gullij** [comment]
nakupanda discovered that I was using a too old version of Bootstrap, 3.0.x isn't supported in Bootstrap3-Dialog any more. We solved the problem by using an older version of b3-dialog.

**Comment by magatz** [comment]
Hello, same problem!
Using Boostrap 3.3.2, jquery 2.1.1 and boostrap3-dialog 1.34.2
Any hint?

**Comment by gullij** [comment]
I'm only guessing but based on what we tested on my problem it could be that the dialog part is missing from Bootstrap, did you create a custom Bootstrap package?
