### ISSUE TITLE
It's posible to add the modals html to any already created div?

### ISSUE THREAD

**Issue by janscas** [nakupanda/bootstrap3-dialog#131]
As long as modals are created dynamically, I use $('body').on('show.bs.modal','.modal', function(){});  to trigger some functions. But it's quite inefficient to attach this to the body. It will be great if we can attach it to some already created div where the modals will be append.

**Comment by janscas** [comment]
Also... trying to bind a function like above will not work for the first time. Don't know why.

**Comment by nakupanda** [comment]
Hi,

I suggest you to use BootstrapDialog.onShow(...) instead of using that one binding on body.

To attach modal stuff on dedicated div, please see https://github.com/nakupanda/bootstrap3-dialog/issues/86

**Comment by nakupanda** [comment]
Please also see this example

http://nakupanda.github.io/bootstrap3-dialog/play/append-to-div.html

Watch the HTML changes in Chrome Dev Tool for example

**Comment by janscas** [comment]
Thanks for your quick response.

Your last example didn't work. The modal is append at the end of the body.
If you inspect it, the modal html is append to the end of the body on the dialog.open() method. It ignores the $('#model-container).append(dialog)

However the example on #86 works but I see <div class="modal-backdrop...>...</div> correctly append inside the modal div instead at the end of the body as you said there.

Doing this #86 stuff can introduce any glich? or it's perfectly fine?

At the end as you said is better to simply use function onshow.
Thanks

**Comment by nakupanda** [comment]
Ok.. sorry for that wrong example.

It's likely because I didn't have enough coffee this morning.

Date: Tue, 17 Mar 2015 02:50:05 -0700

**Comment by janscas** [comment]
Same as me men...

One more question... Do I have to call dialog.realize() every time before calling dialog.getModal()?
I have autodestroy = false but I do change some css properties every time the function is called. I don't really know what realize is doing.

**Comment by nakupanda** [comment]
Ah.. I think that example fails because of lacking of calling dialog.realize() first.

Let me confirm.

Date: Tue, 17 Mar 2015 03:09:17 -0700

**Comment by nakupanda** [comment]
Hi,

Please try this
```
                var dialog = new BootstrapDialog({
                    title: 'Not in body',
                    message: 'But somewhere else.'
                });
                dialog.realize();
                $('#modal-container').append(dialog.getModal());
                dialog.open();
```

I guess the example I sent this morning fails because of missing dialog.realize();

Thank you for the clue!

**Comment by nakupanda** [comment]
The example http://nakupanda.github.io/bootstrap3-dialog/play/append-to-div.html has been updated.

Thanks!

**Comment by nakupanda** [comment]
"what realize is doing."
-----------------------------
It creates Modal stuff, like <div class="modal".../>, and calls bootstrap's .modal('..') to create modal dialog internally.

After the method is called, you can operate any elements inside that modal.

In short, it's a 'initialize' method.


"Doing this #86 stuff can introduce any glich? or it's perfectly fine?"
-----------------------------
No glich but your code might looks a bit verbose. I'm going to add an option 'appendTo' to simplify this as you're not the first one looking for it.

**Comment by janscas** [comment]
Now works perfectly! Thanks!

**Comment by nakupanda** [comment]
No worries :)
