### ISSUE TITLE
Modal closes when inner modal is closed

### ISSUE THREAD

**Issue by nomaanp** [nakupanda/bootstrap3-dialog#133]
Hello @nakupanda 
Thanks for the wonderful plugin. I was just give a try to plugin and faced some issue with multiple modals. I'm facing a problem when using this bootstrap dialog and inside this modal, I'm loading a default modal of bootstrap. When I closes the inner modal, the outer modal also gets closed. 

I looked into the issue and found this one https://github.com/nakupanda/bootstrap3-dialog/issues/102

I looked into the library and found this function 
 
```javascript
isModalEvent:function(e){return typeof e.namespace!=="undefined"&&e.namespace==="bs.modal"}
```
This function is checking the namespace `bs.modal` which both the modals having.

I've created a repository for it [Sample Bootstrap dialog](https://github.com/nomaanp/sample-bootstrap-dialog)

Thanks & waiting for your reply.

**Comment by nakupanda** [comment]
Hi,

Just noticed you're using bootstrap 3.0.3, it's a too old version.

If possible, I would suggest to use a newer bootstrap and see if problems remain.

Thanks for the samples :)

**Comment by nomaanp** [comment]
Hi @nakupanda 
Tried this with latest bootstrap but the first modal(dialog) open & then when I try to open the inner modal, both modals gets closed.

**Comment by nakupanda** [comment]
Hi,

I found below:

1, In remote.html of your sample,  there should be only the modal's stuff, do not put html, body, and bootstrap js / css import statements there, as remote.html will be loaded into index.html and multiple loading causes the problem.

2, Your bootstrap.css is v3.3.1, this causes a backdrop problem.

3, The modal in remote.html was not managed by BootstrapDialog, it has z-index problem.


Hope this helps..

**Comment by nomaanp** [comment]
ok thanks I'll give it a try and let u know...

**Comment by nakupanda** [comment]
look forward to your good news :)

**Comment by nomaanp** [comment]
Hi @nakupanda 
Replaced the default modal code with the plugin code and its working perfectly. Thanks for the worderful plugin. For anyone having problem with multiple modals, I've added the working copy on [my github repository](https://github.com/nomaanp/sample-bootstrap-dialog).
So closing this issue and question.

**Comment by nakupanda** [comment]
Great, thanks for the samples :)
