### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Constructor' of undefined  (modal)

### ISSUE THREAD

**Issue by dleffler** [nakupanda/bootstrap3-dialog#134]
Using TB v3.3.4 & bootstrap3-dialog v1.34.3, I get this fatal error on line #41, since there is no object 'modal' ($.fn.modal.Constructor) to extend.  I do not load the entire bootstrap.js file, simply modal.js & transition.js.

At present I continue to use v1.34.1 with the z-index patch.

**Comment by nakupanda** [comment]
Hi,

Can you please send me your example with modal.js & transition.js ?

**Comment by dleffler** [comment]
I'm unable to upload an html example here
My email is dleffler@hughes.net

**Comment by dleffler** [comment]
Confirmed, and fixed my local code.

**Comment by nakupanda** [comment]
Great :)

**Comment by Legion112** [comment]
Hello!
I got the same problem.

**Comment by gajendrajena** [comment]
Geeting the issue with bootstrap 5
