### ISSUE TITLE
Passing html file's content containt new line characters

### ISSUE THREAD

**Issue by thanhhungtn1** [nakupanda/bootstrap3-dialog#135]
I passed a html file's content which contained new line character via jquery post response to message option of boostrap dialog.
But it auto generated many <br></br> tag inside the modal-body-message which make the html content be broken.
It is fine if I use jquery .html() function.
I think you should build an escape function to remove special characters like new line characters for html instead of replace it with the <br></br> tag which should only be available for text type message.

Finally, I think this is an enhancement :)

**Comment by nakupanda** [comment]
Hi,

Please share the code of how you generated the dialog with html content.

**Comment by thanhhungtn1** [comment]
The response from my posting looks like this:

    \r\n\r\n\r\n\r\n\r\n&lt;!-- Modal --&gt;\r\n&lt;div class=&quot;row&quot;&gt;\r\n\t&lt;div class=&quot;col-lg-6&quot;&gt;\r\n\t\t&lt;table class=&quot;table&quot; style=&quot;font-size: 11px; margin-bottom: 0px&quot;&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Service Type&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;DHL Worldwide Express&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Quote Date&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;07-04-2015&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Package Type&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;Customer packaging&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Job Number&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;10000001AADB&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t&lt;/table&gt;\r\n\t&lt;/div&gt;\r\n\t&lt;div class=&quot;col-lg-6&quot;&gt;\r\n\t\t&lt;table class=&quot;table&quot; style=&quot;font-size: 11px; margin-bottom: 0px&quot;&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Reference#&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;10000001&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Acutal weight&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;0 kg(s)&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Zone&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;1&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;tr&gt;\r\n\t\t\t\t&lt;td class=&quot;td1&quot;&gt;Dim. Weight&lt;/td&gt;\r\n\t\t\t\t&lt;td class=&quot;td2&quot;&gt;0 kg(s)&lt;/td&gt;\r\n\t\t\t&lt;/tr&gt;\r\n\t\t&lt;/table&gt;\r\n\t&lt;/div&gt;\r\n\t&lt;div class=&quot;col-lg-12&quot;&gt;\r\n\t\t&lt;label&gt;\r\n\t\t\t&lt;b&gt;&lt;u&gt;Package Information:&lt;/u&gt;&lt;/b&gt;\r\n\t\t&lt;/label&gt;\r\n\t\t&lt;hr class=&quot;w11&quot;&gt;\r\n\t\t&lt;table class=&quot;table table-hover table-bordeed mg0&quot; id=&quot;datatable1&quot;&gt;\r\n\t\t\t&lt;thead&gt;\r\n\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t&lt;th&gt;Piece&lt;/th&gt;\r\n\t\t\t\t\t&lt;th&gt;Dead weight&lt;/th&gt;\r\n\t\t\t\t\t&lt;th&gt;Cubic weight&lt;/th&gt;\r\n\t\t\t\t\t&lt;th&gt;Quantity&lt;/th&gt;\r\n\t\t\t\t\t&lt;th&gt;Dimension&lt;/th&gt;\r\n\t\t\t\t&lt;/tr&gt;\r\n\t\t\t&lt;/thead&gt;\r\n\t\t\t&lt;tbody&gt;\r\n\t\t\t\t\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;td&gt;1&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td&gt;6&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td&gt;1&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td&gt;6&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td&gt;46.0 x 33.0 x 46.0 cm(s)&lt;/td&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\r\n\t\t\t&lt;/tbody&gt;\r\n\t\t&lt;/table&gt;\r\n\t\t&lt;hr class=&quot;w11&quot;&gt;\r\n\t\t&lt;div class=&quot;row&quot;&gt;\r\n\t\t\t&lt;div class=&quot;text-right pal pdt10 w6&quot;&gt;&lt;/div&gt;\r\n\t\t&lt;/div&gt;\r\n\t&lt;/div&gt;\r\n\t&lt;div class=&quot;col-lg-12&quot;&gt;\r\n\t\t&lt;hr class=&quot;w11&quot;&gt;\r\n\t\t&lt;div class=&quot;col-lg-6&quot;&gt;\r\n\t\t\t&lt;table class=&quot;table table-hover  mg0&quot;&gt;\r\n\t\t\t\t&lt;thead&gt;\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;th&gt;Shipper Address&lt;/th&gt;\r\n\t\t\t\t\t\t&lt;th&gt;Receiver Address&lt;/th&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t&lt;/thead&gt;\r\n\t\t\t\t&lt;tbody&gt;\r\n\t\t\t\t\t&lt;td&gt;\r\n\t\t\t\t\t\t&lt;table&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Outsight Pty Ltd&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Sasha Marks&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Unit 415, 30-40 Harcourt Pde&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;ROSEBERY&amp;nbsp;2018&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t&lt;/table&gt;\r\n\t\t\t\t\t&lt;/td&gt;\r\n\t\t\t\t\t&lt;td&gt;\r\n\t\t\t\t\t\t&lt;table&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Portsmouth Limited&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Leonne Kassler&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;No 2 Portsmouth Rd,&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;Wellington&amp;nbsp;6022&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t\t&lt;td&gt;&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\t&lt;/table&gt;\r\n\t\t\t\t\t&lt;/td&gt;\r\n\t\t\t\t&lt;/tbody&gt;\r\n\t\t\t&lt;/table&gt;\r\n\t\t&lt;/div&gt;\r\n\t\t&lt;div class=&quot;col-lg-6&quot;&gt;\r\n\t\t\t&lt;table class=&quot;table table-hover  mg0&quot; id=&quot;&quot;&gt;\r\n\t\t\t\t&lt;thead&gt;\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;th&gt;Quote Detail&lt;/th&gt;\r\n\t\t\t\t\t\t&lt;th&gt;&lt;/th&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t&lt;/thead&gt;\r\n\t\t\t\t&lt;tbody&gt;\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;- Base Charge:&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;&lt;input type=&quot;text&quot; name=&quot;&quot; value=&quot;174.00&quot; class=&quot;form-control w12&quot; data-placement=&quot;top&quot; placeholder=&quot;&quot; data-toggle=&quot;tooltip&quot; data-original-title=&quot;Tooltip on&quot;/&gt;&lt;/td&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\r\n\t\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;- FUEL SURCHARGE:\r\n\t\t\t\t\t\t\t&lt;/td&gt;\r\n\t\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;&lt;input type=&quot;text&quot; name=&quot;quoteJobDetail.quoteLogDetails.167&quot; maxlength=&quot;25&quot; value=&quot;29.58&quot; id=&quot;quoteJobDetail_quoteLogDetails_167&quot; class=&quot;form-control w12&quot; data-placement=&quot;top&quot; placeholder=&quot;&quot; data-toggle=&quot;tooltip&quot; data-original-title=&quot;Tooltip on&quot;/&gt;&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;- Total Charges:&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;203.58&lt;/td&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t\t&lt;tr&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;&lt;/td&gt;\r\n\t\t\t\t\t\t&lt;td colspan=&quot;2&quot;&gt;&lt;i&gt;Quote is an estimate. Additional fees may apply.&lt;/i&gt;&lt;/td&gt;\r\n\t\t\t\t\t&lt;/tr&gt;\r\n\t\t\t\t&lt;/tbody&gt;\r\n\t\t\t&lt;/table&gt;\r\n\t\t&lt;/div&gt;\r\n\t\t&lt;hr class=&quot;w11&quot;&gt;\r\n\t&lt;/div&gt;\r\n&lt;/div&gt;\r\n&lt;div class=&quot;form-actions text-right pal pdt10 w6&quot;&gt;\r\n\t&lt;button type=&quot;button&quot; class=&quot;btn s33&quot; disabled=&quot;disabled&quot;&gt;Save&lt;/button&gt;\r\n\t&lt;button type=&quot;button&quot; class=&quot;btn s33&quot; data-dismiss=&quot;modal&quot;&gt;Close&lt;/button&gt;\r\n&lt;/div&gt;\r\n\r\n&lt;!-- End Modal --&gt;

This will be show fine if I use jquery .html() to replace the content of the <div>
But if I pass this to message option of the boostrap3-dialog the "\r,\n,\t" will be replaced by the <br></br> tag

**Comment by thanhhungtn1** [comment]
Actually I have removed the escaping function and it showed fine. I understand this is for creating new line in the message if the text containing ending line characters. But it will break the html structure if we replace all the ending line characters by the <br> tags. I suggest to add an options to disable the replacing ending line characters function ;)

**Comment by nakupanda** [comment]
Try to set nl2br: false and see if your problem gets solved

**Comment by thanhhungtn1** [comment]
oh, I didn't realize that there is an option for that.
It solved this problem :) 
Thank you for your really fast support :+1:

**Comment by nakupanda** [comment]
No worries :)
