### ISSUE TITLE
Show location bar of https page

### ISSUE THREAD

**Issue by jqueryhacker** [nakupanda/bootstrap3-dialog#141]
Hello,

I'm loading a https signup form inside a dialog called from an http page using an iframe. I would like a way to show the location bar of the loaded page to confirm to user that the signup form is encrypted.

My initial  code was: 
$(".securePage").click(function(e) {
            e.preventDefault();
            click = true;
            var src = $(this).attr("href");
            var title = $(this).attr("title");
            BootstrapDialog.show({
                message: $('<iframe id="iFrame" src="' + src + '"scrolling="no" height="700"></iframe>'),
                title: title,
            });
        });

but there is no indication that the page loaded is secure.

I tried replacing the message line with
 message: $('window.open(src,title,"height=700")'),

but that just gave blank dialog

Is there a solution  to this problem?

**Comment by nakupanda** [comment]
Hi,

Is there an example that using similar trick to show https status in url bar in a dialog?

**Comment by jqueryhacker** [comment]
I see the message content was missing from my original post. It was

message: $('<iframe id="iFrame" src="' + src + '"scrolling="no" height="735"></iframe>'),

**Comment by nakupanda** [comment]
Please see
http://www.axure.com/c/forum/ask-newbie-question/10057-iframe-wont-display-secure-content.html
http://www.tinywebgallery.com/blog/iframe-do-not-mix-http-and-https

I would like to ask what your problem is, did you see the page loaded in iframe, or you couldn't see anything?

**Comment by jqueryhacker** [comment]
The page loaded but there was no indication that it was an https page, that's why I wanted to show the location bar as below. I have since reverted to  a simple window.open().

![image](https://cloud.githubusercontent.com/assets/1562240/7311370/4490c1e4-e9d7-11e4-9328-65ba0425d358.png)

**Comment by nakupanda** [comment]
Please see http://security.stackexchange.com/questions/894/are-there-security-issues-with-embedding-an-https-iframe-on-an-http-page

I can't seem to google out an example to show native url bar for an iframe.

**Comment by jqueryhacker** [comment]
The window.open() solves my problem. Clearly using a dialog to open an iframe containing an HTTPS is not a good solution.

Thanks for your help. Consider this closed

**Comment by nakupanda** [comment]
It's ok, tried to help but failed :(
