### ISSUE TITLE
CommonJS: Export the factory function

### ISSUE THREAD

**Issue by IngwiePhoenix** [nakupanda/bootstrap3-dialog#142]
I am currently setting up to use WebPack. One issue that I am facing now is, that I am getting a TypeError. It got fixed by changing the line of `module.exports` to:

    module.exports = factory;

I then was able to use it like this:

    var BootstrapDialog = require("bootstrap3-dialog/dist/js/bootstrap-dialog.js")(jQuery);

WebPack tries to resolve `require` calls - however, since it is a web-oriented platform, jQuery does not return it's factory function...instead, it returns itself. An alternative solution would be to test for `window`. Or...do you have another idea? o.o

**Comment by cmwelsh** [comment]
I find this line odd:

```
        module.exports = factory(require('jquery')(root));
```

I would presume it should read like this?

```
        module.exports = factory(require('jquery'));
```

**Comment by IngwiePhoenix** [comment]
That would work, yes. I did suggest the first version because of keeping compatible with existing CommonJS systems. For now I am using a locally modified patch.

**Comment by cmwelsh** [comment]
I had to do the following for webpack support:

        module.exports = factory(require('jquery'), require('bootstrap'));

**Comment by IngwiePhoenix** [comment]
I see. For now my local patch works. I just hope that I wont need to hamsterpatch it in the future… :)

**Comment by nakupanda** [comment]
Hi Guys,

In another issue #145 @KhoaSydney mentioned simply changing 

````
module.exports = factory(require('jquery')(root)); to module.exports = factory
````

Will this cause any problems for you needed?

**Comment by nakupanda** [comment]
Hi,

By combining #142 and #145 , I made this change: https://github.com/nakupanda/bootstrap3-dialog/commit/496d874c52726994edeb5c64c3c57c57aac56f1a

Please review it and, if I made stupid mistake please correct me.. thank you

**Comment by IngwiePhoenix** [comment]
@nakupanda This looks very much like it would work, yes. :)

I am reviewing your latest change now.

**Comment by IngwiePhoenix** [comment]
Yes! :) This is confirmed to work now. Thank you for the fix!

**Comment by KhoaSydney** [comment]
:+1:

**Comment by htulipe** [comment]
@IngwiePhoenix any plan to release this soon? Current 1.34.4 does not have this fix. Thanks for your work on this plugin.

**Comment by nakupanda** [comment]
Thanks for pushing the lazy man.

Here it it: https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.34.5

**Comment by htulipe** [comment]
Thank you so much
