### ISSUE TITLE
Long pages, vertical scrollbar

### ISSUE THREAD

**Issue by ivantcholakov** [nakupanda/bootstrap3-dialog#143]
On long pages, Opera 28:

1. Ordinary bootstrap dialog: The right browser scrollbar disappears, but its place (with) is hold.
2. Monkey-friendly dialog: The right scrollbar disappears totally, and the page width expands to 100%. This kind of blinking I want to avoid.

Is it possible an additional option to be added, so monkey-friendly dialog to behave identically to the ordinary dialog in regard to the vertical scrollbar?

**Comment by nakupanda** [comment]
Hi,

Can you please post an example here to reproduce it ? A jsfiddle example would be the best.

**Comment by ivantcholakov** [comment]
I am backend developer mostly, to show my example in jsfiddle is difficult for me. I am preparing now a demo page on the platform that I am capable to maintain.

**Comment by nakupanda** [comment]
Ok, understood, I will try to create such an example and will give you feedback later.

**Comment by ivantcholakov** [comment]
I have the page: http://iridadesign.com/starter-public-edition-3/www/playground/assign-rating
Here is the code: https://github.com/ivantcholakov/starter-public-edition-3/compare/v3.0.6...v3.0.7
Next, I will explain what I see.

**Comment by nakupanda** [comment]
ok, before that I would like to ask if it's possible for you to update bootstrap? I noticed you're using bs3.0.2 which is a old version.

**Comment by ivantcholakov** [comment]
1. Open the demo page and click on "Assign Ratings" button. A "monkey-non-friendly" dialog appears. The vertical scroll-bar disappears.
2. Click on "Delete" button. A "monkey-friendly" dialog appears. So far so good.
3. Click on "No" button to close the dialog. And then, the vertical scroll-bar appears, it should not.

I'll check the Bootstrap version.

**Comment by ivantcholakov** [comment]
It is normalize.css inside Bootstrap at v3.0.2.
Bootstrap is 3.0.4, compiled by me.

**Comment by ivantcholakov** [comment]
Sorry, Bootstrap is 3.3.4, I wrote it incorrectly in the previous post.

**Comment by nakupanda** [comment]
Hi,

Did you try opening the second dialog with Ordinary bootstrap dialog ? 

Please see https://github.com/twbs/bootstrap/issues/11986

I'm not sure within the latest bootstrap if this problem still exists, but Monkey-friendly dialog should handle this well. In you case you used both types together maybe that's the problem.

**Comment by ivantcholakov** [comment]
I will test your idea.

**Comment by ivantcholakov** [comment]
Yes, there is the same effect. It looks like this problem comes from Bootstrap.

**Comment by nakupanda** [comment]
If the first dialog was opened by BootstrapDialog, I think your problem would get resolved.

**Comment by ivantcholakov** [comment]
I think so too an I will keep this in mind.

It occurred to me an another way, simply to bypass this problem by redesigning the initial main dialog, I put an alert inside - http://iridadesign.com/starter-public-edition-3/www/playground/assign-rating-2

Thank you very much for your time. :)

**Comment by nakupanda** [comment]
No worries :)

**Comment by nakupanda** [comment]
Closing but I can reopen it if needed.
