### ISSUE TITLE
$.fn is undefined

### ISSUE THREAD

**Issue by KhoaSydney** [nakupanda/bootstrap3-dialog#145]
Hi,

I'm currently facing the problem with bootstrap3-dialog using webpack. At runtime, it said `$f.fn is undefined`.  $ is defined and I have tested with alert($) but not `.fn`. Please note that jQuery and Bootstrap are loaded so libraries dependency is not the cause of this error. Is there anything else that might causes the problem?

Cheers,

**Comment by nakupanda** [comment]
Hi,

Is there an online example?

**Comment by KhoaSydney** [comment]
Hi Nakupanda,

Due to complicated setup with Webpack, I can not post it online. I'm thinking this error cause by jQuery conflict. But beside that I can not think of anything else.

**Comment by nakupanda** [comment]
Ok,

So please paste the error details here, let's see if we can find something inside.

**Comment by KhoaSydney** [comment]
I have attached an image which desribes the error. As you can see from the right window panel, $ is defined as a jquery. The left panel show where the error occurred. 

![error](https://cloud.githubusercontent.com/assets/3717031/7383362/55eeb796-ee61-11e4-8a4e-10e6225e549b.png)

**Comment by nakupanda** [comment]
What bootstrap version you're using ?

**Comment by KhoaSydney** [comment]
Bootstrap v3.3.4 

cheers,

**Comment by KhoaSydney** [comment]
Should we wrap the factory function in the following format see if it will fix the issue?

````javascript
function ($) {
  'use strict';
  var version = $.fn.jquery.split(' ')[0].split('.')
  if ((version[0] < 2 && version[1] < 9) || (version[0] == 1 && version[1] == 9 && version[2] < 1)) {
    throw new Error('Bootstrap\'s JavaScript requires jQuery version 1.9.1 or higher')
  }
}(jQuery);
````

**Comment by nakupanda** [comment]
If it doesn't take to too much time I would suggest to do so.

But can you please also provide what jQuery version you're using, and, did you load it prior to bootstrap?

**Comment by KhoaSydney** [comment]
Ok by wrapping it with (jQuery) fixed the error but I have a new error now 

![error](https://cloud.githubusercontent.com/assets/3717031/7383479/6c5f13a2-ee63-11e4-83b8-6f14f46b076e.png)

**Comment by KhoaSydney** [comment]
jQuery JavaScript Library v2.1.3.

**Comment by nakupanda** [comment]
Strange, can't figure it out at this moment

**Comment by KhoaSydney** [comment]
The second fix to the issue from another issue:
https://github.com/nakupanda/bootstrap3-dialog/issues/142

in short change
`module.exports = factory(require('jquery')(root));`  to `module.exports = factory`

I hope this will be useful for other people who have the same problems.

cheers

**Comment by KhoaSydney** [comment]
Hi Nakupanda,

Would you commit fix for the errors mentioned above so that I don't need to add the fix each time I update the package?

cheers,
Khoa

**Comment by nakupanda** [comment]
Hi,

Changes will be committed today, before that please use your local patch, thank you :)

**Comment by KhoaSydney** [comment]
:+1:

**Comment by nakupanda** [comment]
I'm sorry I was too busy today. Will have it done tomorrow.
