### ISSUE TITLE
closable: true  doesn't work

### ISSUE THREAD

**Issue by efkan** [nakupanda/bootstrap3-dialog#146]
Is there any known problem with `closable` property?

I've been using the following libraries into same project with `bootstrap3-dialog`. I checked for library conflicts but couldn't find anything.

- Bootstrap 3.3.4
- jQuery 1.11.2
- bootstrap-notify
- bootstrap-switch
- footable
- form2js
- toObject

**Comment by nakupanda** [comment]
Hello,

What errors you got?

**Comment by efkan** [comment]
Hello, first of all thank you..

When I click anywhere on my screen the dialog doesn't close.

**Comment by nakupanda** [comment]
Did you set closable to true ?

**Comment by efkan** [comment]
Thank you very much @nakupanda,

I've updated my js, css and less files and now it works properly.

I think I had to try this way at first!

**Comment by nakupanda** [comment]
no worries :)
