### ISSUE TITLE
Center Dialog

### ISSUE THREAD

**Issue by slbtuga** [nakupanda/bootstrap3-dialog#149]
Hi.

How can i verticaly center the dialog?

In Bootstrap Modal, i used the following code and it's works fine but dont work for Bootstrap-Dialog.

<code>
$(function () {
    function reposition() {
        var modal = $(this),
            dialog = modal.find('.modal-dialog');
        modal.css('display', 'block');

        // Dividing by two centers the modal exactly, but dividing by three 
        // or four works better for larger screens.
        dialog.css("margin-top", Math.max(0, ($(window).height() - dialog.height()) / 2));
    }
    // Reposition when a modal is shown
    $('.modal').on('show.bs.modal', function () {
        reposition();
    });
    // Reposition when the window is resized
    $(window).on('resize', function () {
        $('.modal:visible').each(reposition);
    });
});
<code>

Regards.

**Comment by nakupanda** [comment]
Hi,

Please try to call reposition() inside onshown() callback:

````
BootstrapDialog.show({
onshown: function() {
    reposition();
}
});
````

Or try others:
https://github.com/nakupanda/bootstrap3-dialog/issues/91
https://github.com/nakupanda/bootstrap3-dialog/issues/46
https://github.com/nakupanda/bootstrap3-dialog/issues/23

**Comment by slbtuga** [comment]
Hi.
Thanks for your reply.

If I call reposition on 'onshown', the dialog center only after fade animation in normal location.
I also try in event 'onshow' but doens't work. I think is because in 'onshow' event, the dialog.height = 0.

<code>
https://jsfiddle.net/pm6e1w0m/2/
</code>

Can you help me with this ?

I tried the others solutions '#91, #46 and #23' but if height of dialog change, the dialog doesn't stay in center.

Another question: Can I bind 'onshow' event ? like for example:
<code>
$('.modal-dialog).onshow( function () {
     centerDialog();
})
</code>

**Comment by nakupanda** [comment]
Hi,

Not sure if you can bind onshow like described.

I tried make a centered modal as you described but failed :( 

I'm sorry for that.

**Comment by nakupanda** [comment]
Closing this as no feedback given.
