### ISSUE TITLE
A request: Spinner as FontAwesome icon

### ISSUE THREAD

**Issue by ivantcholakov** [nakupanda/bootstrap3-dialog#153]
I want to use 'fa fa-spinner fa-fw' class for a button spinner icon, but I don't see a way to do it.

Edit: I mean the 'spinicon' property.

**Comment by nakupanda** [comment]
Hi,

Please see followings:

```
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
```

```
                var dialog = new BootstrapDialog({
                    message: 'Custom spinning icon.',
                    spinicon: 'fa fa-spinner fa-fw',
                    buttons: [{
                            label: 'Spin',
                            autospin: true
                        }]
                });
                dialog.open();
```

You can see a live example here: http://nakupanda.github.io/bootstrap3-dialog/play/spinning-icon.html

I hope this is what you wanted.

**Comment by ivantcholakov** [comment]
Ah, yes. I did not place
spinicon: 'fa fa-spinner fa-fw',
correctly. Your example works for me, thank you.
:-)
