### ISSUE TITLE
Cannot type on select2 when tabindex="-1" 

### ISSUE THREAD

**Issue by kokizzu** [nakupanda/bootstrap3-dialog#155]
Hi, bootstrap dialog prevent typing on `select2` when it has `tabindex="-1"` attribute:

related to this: https://github.com/makeusabrew/bootbox/issues/107

But when removed, the escape key doesn't work correctly.

**Comment by nakupanda** [comment]
Hi,

Can you please create a jsfiddle to reproduce this?

**Comment by kokizzu** [comment]
no, but i can upload the file reproducing the problem:
http://www.filetolink.com/ed28fffd37

**Comment by kokizzu** [comment]
http://192.211.61.196/tabindex-1.zip

**Comment by nakupanda** [comment]
thanks for the example, i'm going to take a further look at it, couldn't find anything at this moment.

**Comment by nakupanda** [comment]
Tried something but still couldn't work it out today :(

**Comment by dylanliang** [comment]
ho!!!how to do now or fix it

**Comment by nakupanda** [comment]
Guys, please create a jsfiddle to reproduce it. 

You can fork this http://jsfiddle.net/Leqckkcn/1/ , it has everything ready.

**Comment by vibintv** [comment]
See this jsfiddle fork http://jsfiddle.net/pwtosqcy/2/  . When removing the tabindex it works fine in google chrome. However removing tabindex in firefox results in misalignment of select. Thank You.

**Comment by nakupanda** [comment]
please see #218

**Comment by nakupanda** [comment]
Closing this as more are described in #218 , reopen when necessary.
