### ISSUE TITLE
Close of secend modal don't work

### ISSUE THREAD

**Issue by aghict** [nakupanda/bootstrap3-dialog#157]
I make modal by these code:
var modal = new BootstrapDialog({
    title: "وضعیت سیستم",
    message: "شروع فرآیند..."
    
});
and when I need modal I use modal.open()
after I reopen modal.open() close button (in header) won't work.

**Comment by nakupanda** [comment]
hi,

please try 
```
autodestroy: false
```

**Comment by yeganehaym** [comment]
not working for me
except close button
action function in buttons is like that

**Comment by nakupanda** [comment]
Looked into the code and found maybe you were using bootstrap 3.3.5?

**Comment by nakupanda** [comment]
Sorry, false assumption. I tried boostrap 3.3.5 and things seemed to be all fine.

**Comment by nakupanda** [comment]
For this case I created a demo page: http://nakupanda.github.io/bootstrap3-dialog/play/reopen-dialog.html

You can view its sourcecode to see if that's what you need.

**Comment by aghict** [comment]
Hello
Thanks 
I add autodestroy: false and know work fine.

**Comment by nakupanda** [comment]
No worries.
