### ISSUE TITLE
AMD requires doesn't include 'bootstrap'

### ISSUE THREAD

**Issue by UptownBob** [nakupanda/bootstrap3-dialog#159]
Line 24 of bootstrap-dialog.js should include 'bootstrap' like this:

define("bootstrap-dialog", ["jquery", 'bootstrap'], function ($) {

You've added bootstrap as a dependency in CommonJS declaration but it was neglected for AMD.

**Comment by nakupanda** [comment]
Thank you, I'm going to add bootstrap.

**Comment by nakupanda** [comment]
Added, please see https://github.com/nakupanda/bootstrap3-dialog/commit/bddb3688936987f04112f91fbfdf760acfed1bac

It will be included in next release.
