### ISSUE TITLE
dialog with html source

### ISSUE THREAD

**Issue by Muhahe** [nakupanda/bootstrap3-dialog#162]
Hello im trying to use your dialog plugin to display form in modal window. I have form already in DOM, and when i display him for first time everything goes well, but form disapear from DOM and when i close dialog and try to open him again, its without form. Is there posibility how to make form not disapear? So it can be reopened multiple times?

**Comment by nakupanda** [comment]
Maybe you can try setting autodestroy: false

Btw can you please share some code snippets?

**Comment by Muhahe** [comment]
yes that was all. sorry for my mistake :(

**Comment by nakupanda** [comment]
No problem :)
