### ISSUE TITLE
Backdrop in front of dialog. Current not compatible with Bootstrap.js v3.3.0.

### ISSUE THREAD

**Issue by WriterStat** [nakupanda/bootstrap3-dialog#165]
Hi! It's peculiar. I checked all the css and everything looks fine.

But as you can see by the picture the backdrop covers the dialog.

Using Bootstrap v3.3.0 and the current version of the bootstrap-dialog just downloaded.

Can I change the z-index of the backdrop and the dialog to sort this out?  Or is there something in the code I need to do?  Wanted ask first. as looks like bug?  For this version?

Is there a best place to do this if I wanted to?  Thanks!  Kinda preventing me from using this. =)

![backdrop](https://cloud.githubusercontent.com/assets/12280348/8510483/7b1967ac-22ad-11e5-8fd6-8fa7283ebc08.png)

**Comment by WriterStat** [comment]
Can I turn off the backdrop?  If I can't put it behind?  Thx!

**Comment by WriterStat** [comment]
After a bunch of testing. Current version of bootstrap-dialog not compatible with Bootstrap.min.js ver3.3.0

If I leave Bootstrap.min.css ver3.3.0 and just change Bootstrap.min.js ver.3.3.0 to Bootstrap.min.js ver.3.3.4 instead.

The backdrop moves back to being behind the dialog correctly.  And works correctly.

The problem is that Bootstrap ver.3.3.0 is still pretty relevant as a base and has some advantages people are using. Just a heads up.

Thoughts on what this might be?  Thanks!  Cheers!

**Comment by nakupanda** [comment]
We have been adding too much in BootstapDialog for compatibility purpose, if you would like to use it for bootstrap 3.3.0, download an older release is a good choice.

I'm sorry I can't help on this :(

**Comment by WriterStat** [comment]
Hi nakupanda! No worries, first I off want to say thank you for making the software.  It's truly cool!

And as someone that does the same and makes software that people use for free, I totally understand.

Totally cool answer.  Was just wondering if I could help. I've cleaned up my posting here to be more of a sign post than a bug.  

* For future people in case they run into the same.  It's possible that 3.3.1 and 3.3.2 in some versions may have the same effect.  I'm not sure if people realize that Bootstrap sort of in some instances keeps the backdrop and the modal separate and sometimes not paired together quite correctly and might have made some changes that might have effected you.

For anyone that reads this where might we find the archived versions?

And I appreciate the quick note back.  And the fine work, believe me I know the the time invested.

And again totally cool answer.

Cheers,

-Colin

**Comment by nakupanda** [comment]
Hi,

So you are still using bootstrap 3.3.0 for some reasons?

**Comment by WriterStat** [comment]
Yup.

**Comment by nakupanda** [comment]
Closing this one as bootstrap 3.3.0 was not in the goal to be supported.

**Comment by johnlui** [comment]
I have the same issus with 3.3.0, and now 3.3.4 is OK.

**Comment by nakupanda** [comment]
@johnlui 

I believe you have made the right choice, upgrading to newer bootstrap is a good way to solve many problems.
