### ISSUE TITLE
jumping body (vertical scrollbar and padding-right bug)

### ISSUE THREAD

**Issue by szegheo** [nakupanda/bootstrap3-dialog#167]
Hi! Please check out this bug when "bootstrap-dialog.js" is loaded in the body tag:
http://codepen.io/anon/pen/eNMrYL

**Comment by nakupanda** [comment]
Hi,

Merged #160, so was this bug fixed along with that too?

**Comment by szegheo** [comment]
I think so. I don't know if it was the real/only reason of this bug, but now it's working fine. Thanks!
