### ISSUE TITLE
Issues closing in Safari 

### ISSUE THREAD

**Issue by toddaa** [nakupanda/bootstrap3-dialog#168]
I am creating the dialog like this:

var dialog = new BootstrapDialog.show({
closable: false,
size: BootstrapDialog.SIZE_WIDE,
message: $("<div></div>').load("newpage.php"),
onshown: function(dialogItself){
dialogItself.getModalBody().find('#btnBack').bind( "click", function(event) {
dialogItself.close();
});
}
});
As you can see its pretty straight forward loading of another HTML page as defined in the documentation. That part works fine. Once the dialog is running I am setting the click event of an element inside the dialog to provide a close button functionality. This seems to work in every browser I have tried except Safari. When the button is pressed, and the close event fires parts seem to close, but main modal dialog remains. Anyone ever heard of this before and know how to get around it?

**Comment by nakupanda** [comment]
Sorry getting this issue so late. I just didn't get notified by email, I think notification was blocked by my mail service provider.

From the code lines you provided, obviously the time spot you tried to get things inside modal body was incorrect, event 'onshown' will be fired when dialog was fully shown - however, this 'shown' status does not contain any results of async request.

I guess dialogItself.getModalBody().find('#btnBack').length is 0 in your example, when it's running failed  in Safari.

**Comment by toddaa** [comment]
Been a while (apologies), but I'm back trying to resolve this issue again.  It seems to be the same in Chrome for me now.  I've updated to the latest version of bootstrap3-dialog, and I'm sure Chrome is pretty current as its hard to tell it no.  

Anyway, Would there be a way to do this from the child page?  If I add an event handler to the #btnBack element on the page that gets loaded into the dialog I mean.  I know javascript has a parent() function, but I am unsure if it would work in this case.  I also don't see an example of this.

Any ideas??

**Comment by nakupanda** [comment]
I have sent your an example my email, I couldn't upload the .zip file here, not sure why.

In the example archive, some files and their contents were as below:

remote.html
````
<button class="btn btn-default" id="btnBack">BACK</button>
````

index.html
````
            var dialog = BootstrapDialog.show({
                title: 'Remote button',
                message: function(dialogItself) {
                    var $message = $('<div>Now loading...</div>');
                    $message.load('remote.html', {}, function() {
                        dialogItself.getModalBody().find('#btnBack').on('click', function(event) {
                            dialogItself.close();
                        });
                    });
                  
                    return $message;
                }
            });
````

index-better.html
````
            var dialog = BootstrapDialog.show({
                title: 'Remote button',
                message: function(dialogItself) {
                    var $message = $('<div>Now loading...</div>');
                    $message.load('remote.html', {}, function() {
                        this.getModalBody().find('#btnBack').on('click', function(event) {
                            this.close();
                        }.bind(this));
                    }.bind(dialogItself));
                  
                    return $message;
                }
            });
````

Hope this helps.

**Comment by toddaa** [comment]
WOW!!!
I did expect and answer so quick, but thank you very much!  That works great!

**Comment by nakupanda** [comment]
No problem :)
