### ISSUE TITLE
Model bar scrollbar disappear when I close the bootstrap dialog

### ISSUE THREAD

**Issue by wstrong** [nakupanda/bootstrap3-dialog#169]
I use bootstrap model and bootstrap dialog together, I call model dialog first which scrollbar work well, and then I call bootstrap confirm dialog, when the confirm dialog closed, the scrollbar of the modal disappear too.

Does anyone know how to solve it? Does it belong to a bug.

**Comment by lov-fan** [comment]
I have encountered this problem too.
i saw that when open a dialog,the <body>  became <body class="modal-open">,
when close second dialog the class 'modal-open' will be removed.
and scrollbar'css was defined by 

.modal-open .modal {
  overflow-x: hidden;
  overflow-y: auto;
}
..................................................
so i add below css code to my jsp' head.
.modal {
  overflow-x: hidden;
  overflow-y: auto;
}

it can be solved.

maybe this solution will cause other Issue,but i have'not find,you can try some other way.

**Comment by lov-fan** [comment]
![image](https://cloud.githubusercontent.com/assets/6645266/8741892/fa0b4b6e-2c91-11e5-98f0-455a8d987361.png)
|
|
![image](https://cloud.githubusercontent.com/assets/6645266/8741904/237110b0-2c92-11e5-8f52-207c31a78d9b.png)

**Comment by lov-fan** [comment]
i saw that when open a dialog,the 
![image](https://cloud.githubusercontent.com/assets/6645266/8741974/edd44a0c-2c92-11e5-93ae-05be29bfc5af.png)
 became 
![](https://cloud.githubusercontent.com/assets/6645266/8741892/fa0b4b6e-2c91-11e5-98f0-455a8d987361.png)
,
when close second dialog, the class 'modal-open' will be removed.
and scrollbar'css was defined by

.modal-open .modal {
overflow-x: hidden;
overflow-y: auto;
}
..................................................

**Comment by wstrong** [comment]
yes, I find a way to avoid it. Thanks.
            $(document).on('hidden.bs.modal', function () {
                    $('body').addClass('modal-open');
            });

**Comment by nakupanda** [comment]
What bootstrap version and what bootstrap-dialog version you're using ?

**Comment by lov-fan** [comment]
bootstrap/3.3.4
and 
bootstrap3-dialog/1.34.3

and addClass,something wrong,when you close all dialog ,cant scroll body...

**Comment by wstrong** [comment]
bootstrap/3.3.4

**Comment by wstrong** [comment]
bootstrap3-dialog/3.4.3.1

**Comment by nakupanda** [comment]
wstrong, the first dialog you opened using bootstrap-dialog or bootstrap itself's ?

**Comment by nakupanda** [comment]
Bootstrap has an internal container to hold all dialogs it opened, scrollbar should have been displayed or hidden correctly.

**Comment by nakupanda** [comment]
Hi guys,

Anyone can create a js fiddle to reproduce this problem ? thanks.

**Comment by lov-fan** [comment]
yes, its due to that i use bootstrap itself's dialog,
if i use bootstrap-dialog totally,there's no problem.

**Comment by wstrong** [comment]
nakupanda, the first dialog is bootstrap modal dialog, second is bootstrap-dialog. The problem has been solved. Thanks for all your nice help.

**Comment by nakupanda** [comment]
No worries :)
