### ISSUE TITLE
How to make dialog truly modal? Current dialog can and will open multiple duplicate instances.

### ISSUE THREAD

**Issue by WriterStat** [nakupanda/bootstrap3-dialog#170]
Hi! How does one make the dialog modal? Allowing only one instance displayed at a time?

Not currently modal.

Example: attach the show or new dialog to a link, put that link in a div and set that div as fixed/on top, like a regular menu style.

Click the link. Click again. Each time you do. Another instance of the dialog and backdrop is created on top of the previous one.  And so on...

Wondering if there is code inside to limit it to one current instance?

Being a modal dialog I need to make sure there's only one instance created. Thx!

Is there a setting or code I can use?

**Comment by nakupanda** [comment]
Hi,

How about to create an instance but do not open it immediately?

When page is loaded:

````
var onlyOneDialog = new Bootstrap({....});
````

And in your link's event handler:
````
$link.on('click', function() {
     onlyOneDialog.open();
});
````

I haven't tried this yet..

**Comment by WriterStat** [comment]
Hey Much Thanks for the quick response.

Will give it a try.  Right now I create and open the modal dialog together in a function based on the help docs.  

I guess I could open one global blank instance, as you mentioned.  Long night, didn't think of that. =)  Thanks!

**Comment by nakupanda** [comment]
No problem :)

**Comment by WriterStat** [comment]
Hey Morning!  I think maybe the issue with doing it this way, is recreating the confirms, alerts, and redoing all the options, parameters etc...helper code things you've done, each time, and doing it as a singleton as a global external var.  Will it effect the dialog software in any way, all this constant reuse without resetting.  And then having to have a global instance, that needs to be set by calls instead of options. To have the modal window be, well truly modal as an alert of confirm etc... 

Might be easier to have an internal option for modal/not modal, so that it could do some self cleaning and so we could just use all the great helper code etc...from the demos, without it creating multiple instances of the code/object. Hope this helps.

Doing a New, would of course produce a new object.  But show(), Confirm(), alert() etc...probably shouldn't create new instances on top of each other, being they are well to be modal. =)

The reuse should be in the code for a modal window object or a close and reopen.

I'll again see what I can do with the above, But I have show() and confirm etc...

And I'm not sure if I can do as you suggest with, s_dialog.confirm({...}) instead of BootstrapDialog.confirm({...}); And how/if that will work.  Haven't tried it yet.

Cheers, and thanks!  Any thoughts much appreciated.

**Comment by nakupanda** [comment]
Ok, back to the first question, to have only one instance displayed at a time, you can:

````
$link.on('click', function() {
     BootstrapDialog.closeAll(); // Close all opened dialogs before opening new one.
     BootstrapDialog.show({...});  // New one.
});
````

**Comment by WriterStat** [comment]
Cool! =)  Note: I tried doing this using the .close(), but each time I did. It basically shutdown the interface, wouldn't allow me to open or show any new ones after I did.

I'm guessing this works best. Note: Can I make the call above, without any dialogs being opened? Example: a generic open modal dialog call should always check first or if not remove the current opened one and give the expected behavior.

Long term, the modality of the Modal Dialog, alert, confirm etc... should be handled internally as an option switch.  I or the user clicking on another separate action shouldn't really be allowed to circumvent it.

However having the ability to make a modal dialog non-modal is a cool feature as an option in the software.

**Comment by WriterStat** [comment]
Ok, gave this a try...

I called an onclick function that has BootstrapDialog.show({...}); in it to open a dialog.

It opens.

In my 2nd function that I call on click of a link I have placed...

     BootstrapDialog.closeAll();
     BootstrapDialog.show({...});

As above.

I expect it to close the first dialog and then open the second.

However nothing happens, it doesn't close the first dialog, nor does it open the second.

In fact, in the current code here it disables the use of that link code entirely, so no dialogs will open after that if you click it.

Could you do a fiddle showing this as a modal? Just to make sure it's working in the current version?  Or do I need an updated version?  Thanks!

Note: If I comment out the BootstrapDialog.closeAll(); in the code above everything goes back to working just fine.  Dialogs open just fine from the link. 

Any help much appreciated.  Looks like you close, but not show in the same code area which is weird.

**Comment by nakupanda** [comment]
I saw your other feedback in email notifications but seems they have been removed here.

So did you find a way to achieve what you wanted?

**Comment by WriterStat** [comment]
Hey NakuPanda! Good morning, morning here now. Thanks for the quick response.

You are great! And I can't say how much I appreciate the tips and help, really cool!

No worries, everything worked out fine. =) I wrote as I was thinking through things.  Then basically changed my thinking.

So all good.

Not many people will probably try it like I did.  From fixed areas/divs.  And so most will be behind the backdrop.  

As a really quick fix, I did a quick edit to your fine code.

Created a modal option/param setting for the object. =)  Basically {modal: true/false} 

Placed the closeAll() in the open event if (modal == true) 

Checked for existing DialogRefs and then closeAll().

Doing it inside your code seemed to clear up any problems, made things accessible.

I did notice if I call:

var dialog = new BootstrapDialog({....}); 
dialog.open();

In one function and then in another function call

BootstrapDialog.closeAll();
BootstrapDialog.show({...});

It doesn't close the original one above. And sort of stops the original function from working and opening any new dialogs after the original call.

Prolly just me. Not sure why. =)

Anyways thanks for the fine code and let me know if there's anything I can ever do for you.

Cheers,

-C

**Comment by nakupanda** [comment]
No worries, when I have time I'm glad to help everyone like how everyone helped me.

Here is an example page http://nakupanda.github.io/bootstrap3-dialog/play/only-one-dialog.html

Not sure if that's closed to your idea, just take a look at it :)

**Comment by nakupanda** [comment]
I bet you cannot open more than one dialog in above page.

**Comment by WriterStat** [comment]
Sup NakuPanda! =)  Pretty close, sure.  =)  Thanks!

Like I said above in my note prior to the two above here, I edited your Dialog code directly already.  

And moved all that into your code base into the open event and put in a modal option setting for the object. =)
 
Basically {modal: true/false} Which cleared things up.  Being that the closeAll() was always called first now in the edited BootstrapDialog code base I use here.

I could open a trunk or commit if you want.  Let me know.  Or you could do it quick.  If you follow what I did in the note above yours.  It's only a few lines.

* This edit to your code fixes the problem with the confirm and alert etc... not being truly modal. Especially In instances where they are called from a fixed div or div with a higher z-index than the BootstrapDialog and Backdrop to it have.

This allows a person to turn the modality on and off directly in your code, once only needed. And keeps the users/developers/programmer from having to write that extra line above each and every  confirm, alert etc... every time.

* With that said, still doesn't clear up the general problem that calling the closeAll() or close() from a separate 2nd external function as I outlined in my note above, after a new has been performed in an earlier already running function can cause unexpected results.  

It just shifts the close all to always be above the... new BootstrapDialog({....});  Where it doesn't cause a problem.

But that's a problem for another day.

So I closed this.
