### ISSUE TITLE
Dialog Could Not Close

### ISSUE THREAD

**Issue by felaozhiyong** [nakupanda/bootstrap3-dialog#173]
I create a dialog like this : 
var dialog = new BootstrapDialog({
    title:"test",
    message:"Hello"
}).realize();
$("#myBtn").on("click",function(){
    dialog.open();
})
I did follows action:
1.click myBtn to open dialog , and click the "X" button to close it. It' OK
2.I clikc myBtn to open it again, and click the "X" button to close it, it can not be closed . I click the mask can hide the dialog , but it  was not be clear. and the "X" button had been invalid , when opened again.

**Comment by nakupanda** [comment]
By default everything will be destroyed after it's closed.

To change this default behavior you can set autodestroy: false.

````
var dialog = new BootstrapDialog({
title:"test",
message:"Hello",
autodestroy: false
}).realize();
````

**Comment by felaozhiyong** [comment]
Thanks !

**Comment by nakupanda** [comment]
No problem.
