### ISSUE TITLE
Use .html() to copy template will appear <br> , Is it a bug ?

### ISSUE THREAD

**Issue by felaozhiyong** [nakupanda/bootstrap3-dialog#174]
template like this : 
<div id="myDialog" style="display: none">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3"><div class="btn btn-primary">Button</div></div>
    </div>
</div>
I crete a dialog : 
var dialog = new BootstrapDialog({
    title:"test",
    message:$("#myDialog").html()
}).realize();
when it opened , there were many <br> in dom
I must write it like that $("#myDialog").html().replace(/\n/'g')
Is it a bug ?

**Comment by nakupanda** [comment]
It's not a bug, 

You can turn this behavior off by setting option nl2br: false

````
var dialog = new BootstrapDialog({
title:"test",
message:$("#myDialog").html(),
nl2br: false
}).realize();
````

**Comment by felaozhiyong** [comment]
Thanks !

**Comment by nakupanda** [comment]
No problem :)
