### ISSUE TITLE
BootstrapDialog.closeAll() fails in a certain case

### ISSUE THREAD

**Issue by ivantcholakov** [nakupanda/bootstrap3-dialog#176]
I have a single page that combines all of your tests. But for this topic these two tests are interesting to be paced in one page:

"Reopen dialog" - https://github.com/nakupanda/bootstrap3-dialog/blob/master/examples/play/reopen-dialog.html
"Only one dialog" - https://github.com/nakupanda/bootstrap3-dialog/blob/master/examples/play/only-one-dialog.html

This is what I observe:

If the page is loaded and the button "Open one dialog" is pressed, then within  BootstrapDialog.closeAll() the following error appears: "Cannot read property 'modal' of undefined"

If the page is loaded and "Reopben dialog" has been opened at least once, then "Open one dialog" works.

Here is my sample code for illustration:

```javascript
    $(function () {

        // Create your dialog but do not open it.
        var dialog_reopen = new BootstrapDialog({
            title: 'Your dialog',
            message: 'This dialog can be opened and closed again and again.',
            autodestroy: false
        });

        $('#reopen_dialog').on('click', {dialog: dialog_reopen}, function(event) {
            event.data.dialog.open();
        });

        // See how to limit only one dialog can be opened at a time.
        var btn_open_only_one_dialog = $('#open_only_one_dialog');
        btn_open_only_one_dialog.on('click', function(event) {
            // The previous example "Create your dialog but do not open it"
            // causes the error "Cannot read property 'modal' of undefined"
            // within BootstrapDialog.closeAll();
            try {
                BootstrapDialog.closeAll();
            }
            catch (err) {}
            var dialog = new BootstrapDialog({
                message: 'The only one.'
            });
            dialog.open();
        });

    });
```

**Comment by nakupanda** [comment]
Hi,

I couldn't get the same error by running above code lines. What version of bootstrap you were using ?

**Comment by ivantcholakov** [comment]
Bootstrap v3.3.5
Here is my test: http://iridadesign.com/starter-public-edition-3/www/playground/bootstrap-modals

**Comment by nakupanda** [comment]
Thanks @ivantcholakov  , I confirmed it was my mistake. See this commit for more details https://github.com/nakupanda/bootstrap3-dialog/issues/176

**Comment by nakupanda** [comment]
The problem was that if .close() method gets called on a unrealized, unopened dialog instance, when closing it has no .modal function attached yet and the error you pasted at the top will be thrown.

Thank you for posting so many helpful information :)

**Comment by ivantcholakov** [comment]
I've tried your correction, it works, thank you. :-)
