### ISSUE TITLE
Making "Fade" an option

### ISSUE THREAD

**Issue by proludio** [nakupanda/bootstrap3-dialog#177]
Sometimes, I just want the dialog to appear (and preferable centered), with a message.
I am assuming it would mean just removing the "fade" class when the dialog is created, but I dont see that it is actually being set.

But my dialog is fading in, and by the time it is displayed, my background task is done.

**Comment by proludio** [comment]
Now I see in the code that there is an option that "animate" can be set to false.

I was looking just a the list of options on
http://nakupanda.github.io/bootstrap3-dialog/#available-options

**Comment by nakupanda** [comment]
I confirmed the example page is out of maintain...

**Comment by nakupanda** [comment]
Closing this one, and all options will be documented later.
