### ISSUE TITLE
backdrop options

### ISSUE THREAD

**Issue by imbooo** [nakupanda/bootstrap3-dialog#178]
how to  show or hide backdrop ?

**Comment by nakupanda** [comment]
no, there is no way to show/hide backdrop individually.

**Comment by nakupanda** [comment]
However, you might be possible to access backdrop via something like 
```
var $backdrop = this.getModal().data('bs.modal').$backdrop;
$backdrop.hide();
```

**Comment by Guam** [comment]
It would be nice to have an option to set the backdrop to hidden such as:
BootstrapDialog.show({
            message: 'Hi Apple!',
            backdrop: 'hidden',
            draggable: true
        });

**Comment by nakupanda** [comment]
That will be under consideration, thank you :)
