### ISSUE TITLE
webjars bower and WebJarAssetLocator tool.

### ISSUE THREAD

**Issue by sugimoris** [nakupanda/bootstrap3-dialog#179]
When use webjars bower and WebJarAssetLocator tool, org.webjars.MultipleMatchesException is thrown, because "examples" directory contains bootstarp.css and bootstrap.js.

**Comment by nakupanda** [comment]
Can directory 'examples' be ignored by configuring webjars ?

**Comment by sugimoris** [comment]
yes, I can not ignore directory 'examples'.

**Comment by nakupanda** [comment]
Please see notes of this release https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.34.6

**Comment by sugimoris** [comment]
Thank you so much.
