### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Izopi4a** [nakupanda/bootstrap3-dialog#182]
Anyone has problems with installing the plugin via composer ?

```
 php composer.phar require cross-solution/bootstrap3-dialog

  [InvalidArgumentException]
  Could not find package cross-solution/bootstrap3-dialog at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

```

this is what I get as an error

**Comment by DiegoWtf** [comment]
+1

**Comment by nakupanda** [comment]
anyone has a solution for this..

**Comment by Izopi4a** [comment]
php composer.phar require cross-solution/bootstrap3-dialog:dev-master@dev

**Comment by DiegoWtf** [comment]
Ok. I see some error during installation but i think that all been installed
![bs-dialog1](https://cloud.githubusercontent.com/assets/8034654/10308398/234e882e-6c3e-11e5-8f66-78c39c542465.jpg)

**Comment by Izopi4a** [comment]
@DiegoWtf 
i think you dont have git installed on your machine ?

```
$ git --version
```

**Comment by DiegoWtf** [comment]
@Izopi4a
You right

**Comment by Izopi4a** [comment]
you pretty much always need git with composer
