### ISSUE TITLE
Close dialog from remote page?

### ISSUE THREAD

**Issue by fastport** [nakupanda/bootstrap3-dialog#185]
Hi @nakupanda,

First of all, love this project and the work you're doing here! I use it for one of my projects at work and really love the way the dialogs behave and look.

However, I'm facing a problem here: I have a remote page that's loaded into the Dialog. After I hit a button on that page, says "Save", I would like for the dialog to close itself. There doesn't seem to be such a feature on the documentation.

I have also tried giving the dialog an ID and then use $("#myModal").modal("hide") or $("#myModal").modal("toggle"), but that didn't work either.

I'm hoping you can help pointing me towards the right direction here. If there isn't such a feature, I think you should consider adding one. Just my opinion. Anyhow, please advise!

Best regards,

**Comment by nakupanda** [comment]
This way can work:

````
                var dialog = new BootstrapDialog({
                    message: $('<div />').load('close-in-remote-message.html')
                });
                dialog.open();

                $('body').delegate('#btn-close', 'click', $.proxy(function (event) {
                    this.close();
                }, dialog));
````

In remote page:
````
<button class="btn btn-success btn-block" id="btn-close">Close the dialog</button>
````

**Comment by nakupanda** [comment]
Below will work too:

````
                var dialog = new BootstrapDialog();
                dialog.setMessage($('<div />').load('close-in-remote-message.html', $.proxy(function(){
                    this.getModalBody().find('#btn-close').on('click', {dialog: this}, function(event){
                        event.data.dialog.close();
                    });
                }, dialog)));
                dialog.open();
````

The key is: to find the button

**Comment by longpham91** [comment]
Hi @nakupanda,

The 1st method worked when I changed "this" to "dialog". Otherwise, the whole window closes.

The 2nd method works great :).

Anyhoo, thanks so much for the solutions. It might be helpful to add this to the documentation too!

Best regards,

Leo

**Comment by nakupanda** [comment]
No problem.

I'm considering a new documentation actually :)
