### ISSUE TITLE
Customize Confirm Modal

### ISSUE THREAD

**Issue by lsotov** [nakupanda/bootstrap3-dialog#187]
Hi, 

I've been trying to customize confirm dialog, but neither the title or the message are being set properly.
I'm using this code:
var msg = 'Are you sure you want to delete this item?';
                BootstrapDialog.confirm({
                    title: 'Delete',
                    message: msg,
                    type: BootstrapDialog.TYPE_DEFAULT, // <-- Default value is BootstrapDialog.TYPE_PRIMARY
                    closable: false, // <-- Default value is false
                    draggable: false, // <-- Default value is false
                    btnCancelLabel: 'Cancel', // <-- Default value is 'Cancel',
                    btnOKLabel: 'Delete', // <-- Default value is 'OK',
                    btnOKClass: 'btn-danger', // <-- If you didn't specify it, dialog type will be used,
                    callback: function (result) {
                        debugger;
                        if (result) {
                            // code omitted 
                        }
                    }
                });

Message is displayed empty and title 'Confirmation'

Regards,

**Comment by nakupanda** [comment]
Hello, please see this jsfiddle

http://jsfiddle.net/k8gpqxx8/1/


Same code lines copied from you mentioned

**Comment by lsotov** [comment]
Hi, I updated to latest version and it's working.

Regards,

**Comment by nakupanda** [comment]
You problem :)
