### ISSUE TITLE
Add button

### ISSUE THREAD

**Issue by jhayjasa** [nakupanda/bootstrap3-dialog#194]
Hi,

First of all thanks for the wonderful dialog script. Works great!
Not really an issue but, is there a quick way I can create buttons in the modal dynamically.

Lets say, I already have an existing submit button on the modal that would trigger an ajax request to the server, when the request is complete I would like to create additional buttons that would have another ajax function. 

Thanks in advance for any help!

**Comment by nakupanda** [comment]
Please see this fiddle
http://jsfiddle.net/Leqckkcn/1/

**Comment by jhayjasa** [comment]
Hi nakupanda,

this is great! I just have to define my own actions and this is exactly what i need. Thanks for the great help. :)

**Comment by nakupanda** [comment]
not a problem :) 

let me know whenever i can help.
