### ISSUE TITLE
can hide title and status bar

### ISSUE THREAD

**Issue by netxixi** [nakupanda/bootstrap3-dialog#195]
thank you for your  dialog plugin!very good!
i want hide the title bar and status button bar,
 center the title text
and extend the prompt dialog,iframe dialog to watch video
thank you very much.

**Comment by nakupanda** [comment]
try this 

http://jsfiddle.net/r7ss165w/1/

**Comment by netxixi** [comment]
thankyou very much! I read the source code! 

发自我的 iPhone

**Comment by nakupanda** [comment]
No problem :)
