### ISSUE TITLE
How to prevent close?

### ISSUE THREAD

**Issue by geoidesic** [nakupanda/bootstrap3-dialog#199]
I have a modal with the normal "x" close button and also with a button at the bottom of the content that issues a .close() call when clicked. Under certain circumstances, I'd like to prevent the dialogue from being closed when either of these are clicked.

Is there already a way to do this?

I tried returning false from the "onhide" method but that didn't do the trick.

**Comment by geoidesic** [comment]
I must be going mad. Thought I tried this already but returning false from "onhide" seems to work after all.

**Comment by geoidesic** [comment]
No wait. It doesn't. Works sometimes other times not. Confused.

**Comment by nakupanda** [comment]
please try this http://jsfiddle.net/ugy18t8y/1/

**Comment by nakupanda** [comment]
ah... sounds you have found the way out.
