### ISSUE TITLE
"closable" doesn't work when re-open the dialog

### ISSUE THREAD

**Issue by KayKwon** [nakupanda/bootstrap3-dialog#202]
As mentioned, closable option works only for very first open. When I close then re-use the dialog, closable doesn't work. I want let a user wait until ajax ends, but it cannot block a user input since the second click event hits.

```javascript
var dialog = new BootstrapDialog({
        title: 'Now loading...',
        message: '<p>my message</p>',
        type: BootstrapDialog.TYPE_WARNING,
        closable: false,
        closeByBackdrop: false,
        closeByKeyboard: false,
    });
g_loading = {spin: spinner, dialog: dialog};   // assign to global variable

var clickEvent = function(oEvent) { // click event handler
        // open the dialog, click event htis multiple times
        g_loading.dialog.open();
        // ajax function call
        geolocationQueryAjax(postData=postData, cLatLng=cLatLng, oMap=oMap);
    };

function geolocationQueryAjax() {
    return $.ajax({
        url: 'geolocation_info',
        type: 'POST',
        data: postData,
        dataType: 'text',
        success: function(data, textStatus, xhr) {
           // some work for success
        },
        error: function(xhr) {
           // work for error
        },
        complete: function(xhr, textStatus) {
            g_loading.spin.stop();
            g_loading.dialog.close();
        },
    });
}
```

**Comment by nakupanda** [comment]
Please fork this and create an example to show the problem: http://jsfiddle.net/o5k0eaws/1/

**Comment by KayKwon** [comment]
@nakupanda I've forked :smile: and described the problem here, http://jsfiddle.net/o5k0eaws/25/
The first time, dialog does not response with any click event. Yet when you re-open the dialog, ```closable: false, closeByBackdrop: false, closeByKeyboard: false,``` does not work.

**Comment by nakupanda** [comment]
Setting option autodestroy to false solves the problem, please see http://jsfiddle.net/3oqpL4o5/

**Comment by KayKwon** [comment]
I wasn't noticed ```autodestroy``` option. Thanks @nakupanda

**Comment by nakupanda** [comment]
No problem :)
