### ISSUE TITLE
How to delete instance of the dialog with autodestroy: false

### ISSUE THREAD

**Issue by jersingh** [nakupanda/bootstrap3-dialog#204]
I've set autodestroy to false but end up with duplicate html in the dialog after a close and open.

I did not see a destroy method anywhere.

Is there a way to do this?

**Comment by nakupanda** [comment]
There shouldn't be duplicate html if you were calling open and close methods on the same instance, but if you did see that happened I believe you can remove those html by doing followings:

````
dialog.setAutodestroy(true);
dialog.close();
````

Or if you are not able to get the instance reference, do similar in onhide callback:

````
onhide: function(dialog) {
     dialog.setAutodestroy(true);
}
````

Hope this can fix your problem, let me know if not.

**Comment by jersingh** [comment]
Thanks for the reply.

I need autodestroy set to true. Should that be:
dialog.setAutodestroy(false);

**Comment by jersingh** [comment]
Problem solved. I found my error. I was re-initializing the dialog every time and not calling dialog.open() on subsequent calls.

Thanks for your response though. I appreciate you getting back to me on this even though it was my error.

**Comment by nakupanda** [comment]
No problem :)
