### ISSUE TITLE
Try to create a modal window fails

### ISSUE THREAD

**Issue by aducom** [nakupanda/bootstrap3-dialog#205]
Regarding javascript I'm a novice, so most likely I'm doing something wrong. I have an ajaxevent and after finish I want to show a message. This is done in a separate .js file:

from the sample:

    function showMessage(theMsg) {
                var dialog = new BootstrapDialog({
                    message: 'Custom tabindex.',
                    tabindex: 10
                });
                dialog.open();
    }         

this is called from a buttonclick that performs the ajax call and then shows message.

    $("#id_main_dbnavigator_1_first").click(function() {
      var str='';
      str = $( "#id_main_form_1" ).serialize();
      procbutton(str+'&cmd=First');
      showMessage('hallo');
    }); 

But nothing pop's up. I tried to debug with firebug, but there's no real informative errormessage. I also tried it in the ajax call back which doesn't work either:

    function procbutton(str) {
      $.getJSON('main.php?component=main_form_1&offset=0'+'&'+str, function(data){
       $.each(data, function(recx, recval) {
        switch(recx) {
        case 'properties' :
          $.each(recval, function(elex, elev) {
              obj=elex;
      	    $.each(elev, function(selex, selev) {
    //more code
             });
           });
           break;
        case 'rows' :
           $.each(recval, function(elex, elev) {
      	    $.each(elev, function(selex, selev) {
                 $("#"+selex).val(selev);
             });
           });
           break;

        default : break;
        };
      });
     });
      showMessage('hallo');
      }

**Comment by nakupanda** [comment]
Hi,

I'm glad to help.

You mentioned nothing pops up and no error message seen, how about changing your second code snippet to:

```
$("#id_main_dbnavigator_1_first").click(function() {
alert('You clicked something.');
}); 
```

This ensure you have correctly applied a callback to the element '#id_main_dbnavigator_1_first'.

**Comment by aducom** [comment]
Yes, that does work. If I remove the showMessage everything works as expected. The json message is send/retrieved and parsed, fields are enabled/disabled and the data is shown in the fields. The only thing I cannot get to work is the popup message to confirm an update i.e. 
 If I set all things up from the samples is does work (as stand alone). As soon as i place the code in a .js things stop working. That's why I expect that I have to add some kind of div placeholder, but I don't know how.

**Comment by aducom** [comment]
As expected it's an error of myself. If you look at getbootstrap.com then you will see at the samples that bootstrap is loaded at the end of the html for performance reasons. I overlooked and have put the dialog js in the header. Then it's obvious that it doesn't work as the bootstrap js needs to be loaded first. An 'aha' moment and I hope others can learn from it too.

**Comment by nakupanda** [comment]
You are actually able to load bootstrap-dialog at the end of the page, but you will need to put your custom code lines after the loading statements or, put your custom code lines inside something like 'onload' or 'documentready', just like how you would use jQuery in your project.
