### ISSUE TITLE
Opening a dialog while closing another leads to miscalculated z-indexes

### ISSUE THREAD

**Issue by Datyedyeguy** [nakupanda/bootstrap3-dialog#208]
JSFiddle showing the issue.

https://jsfiddle.net/g16phmxh/

Perhaps whenever a dialog is initialized, the z-indexes are updated for every modal dialog so that their values are always correct?

Let me know if you have any questions.

**Comment by nakupanda** [comment]
Hi @Datyedyeguy ,

I'm so sorry for missing this, your example makes a lot of senses. I'm now looking into it.

**Comment by nakupanda** [comment]
Bug confirmed, thanks for your findings!

**Comment by nakupanda** [comment]
Patched.

**Comment by nakupanda** [comment]
It should be working now, closing the issue.
