### ISSUE TITLE
May I disable buttons on the confirm dialog and make one spinning?

### ISSUE THREAD

**Issue by andrconstruction** [nakupanda/bootstrap3-dialog#210]

**Comment by andrconstruction** [comment]
It just a question. not an issue. I don't understand how to get buttons in a callback

**Comment by nakupanda** [comment]
So have you found the way?

**Comment by andrconstruction** [comment]
Of course I can do it programmaticaly but I thougth that app has a standard method like a  dialog.enableButtons(false|true)  for a confirm dialog too

**Comment by nakupanda** [comment]
OK, it's doesn't have such a method.

I'm going try to add something to achieve what you were looking for.

**Comment by nakupanda** [comment]
Please see here http://jsfiddle.net/o5k0eaws/68/

At the bottom:

````
BootstrapDialog.confirm('Hi Apple, are you sure?', function (result) {
    alert(result);

    var $button = this;	// The button clicked
    var dialog = $button.dialog;

    // Spin the clicked button, disable all buttons.
    $button.spin();
    dialog.enableButtons(false);

    // Close dialog after 5 seconds clicking on the button
    setTimeout(function () {
        dialog.close();
    }, 5000);

    // Do not auto close the dialog by returning false here
    return false;
});
````

**Comment by nakupanda** [comment]
Download the latest here https://github.com/nakupanda/bootstrap3-dialog/archive/master.zip

It will be included in the next release.

**Comment by andrconstruction** [comment]
Cool, Outstanding! THANKS

**Comment by nakupanda** [comment]
no problem.
