### ISSUE TITLE
btnCancelClass?

### ISSUE THREAD

**Issue by dextreza** [nakupanda/bootstrap3-dialog#213]
there is a btnOkClass option for customization but not a  btnCancelClass option. ¿it would be posible to add it? thanks

**Comment by nakupanda** [comment]
Sorry for replying this too too late, will add it :)

**Comment by dextreza** [comment]
thanks, don`t worry :)

**Comment by BabuBahir** [comment]
plz add btnCancelClass ...its still not there i guess

**Comment by euangordon** [comment]
Still not there.
