### ISSUE TITLE
Auto close a dialog

### ISSUE THREAD

**Issue by GertAC** [nakupanda/bootstrap3-dialog#214]
How can i auto-close a bootstrap3-dialog in ... lets say,  5 sec.

I can delay the opening like this: http://jsfiddle.net/Lu4z5ssj/

but not the other way around.

/Gert

**Comment by nakupanda** [comment]
You have many ways, one of them is like this http://jsfiddle.net/q19115gm/1/

**Comment by GertAC** [comment]
OHH my good that was quick. 
Thanx a lot and marry xmas. :-)

**Comment by nakupanda** [comment]
No problem :)
