### ISSUE TITLE
Message from opened remote.html

### ISSUE THREAD

**Issue by Sityle** [nakupanda/bootstrap3-dialog#217]
Hallo im using 

BootstrapDialog.show({
      message: $('<div></div>').load('remote.html')
});

Now i want to close the dialog by sending a message to the opener in the remote.html over javascript or is there any way to do that ?

**Comment by nakupanda** [comment]
Something related: https://github.com/nakupanda/bootstrap3-dialog/issues/185

**Comment by Sityle** [comment]
Ok this works for the beginning but there is another problem. In the remote.html i call the  "window.setTimeout" function for a javascript countdown. This way:

var setTimeOut = window.setTimeout('countdown('+ --time+',\''+id+'\')', 1000);

Now when the user closes the dialog the setTimeout-Function is still working so that a problem accours when the user opens the dialog again my countdown doesnt work. To kill the setTimeoutFunction the opener need to get the setTimeout variabel to kill it. But i cant image how to do that.

**Comment by nakupanda** [comment]
Modify:
````
var setTimeOut = window.setTimeout('countdown('+ --time+',\''+id+'\')', 1000);
````
To
````
window.aTimer = window.setTimeout('countdown('+ --time+',\''+id+'\')', 1000);
````

Then you should be able to call clearTimeout() anytime you want:
````
clearTimeout(window.aTimer);
````

**Comment by Sityle** [comment]
Thanks that worked perfectly !

**Comment by nakupanda** [comment]
No problem :)
