### ISSUE TITLE
cursor not showing ( use select2) when dialog show

### ISSUE THREAD

**Issue by playcodebyflapjack** [nakupanda/bootstrap3-dialog#218]
Hi everybody ,

I'm find bug when I'm load the content from file . My file have content with use select2
#problem 
cursor is not found
![2015-12-28_10-13-15](https://cloud.githubusercontent.com/assets/6084576/12013905/731d2d82-ad53-11e5-948a-aaed0fbd28f3.jpg)

I'm try remove tagname(tabindex) so cursor is show 

![2015-12-28_10-16-26](https://cloud.githubusercontent.com/assets/6084576/12013928/d7a197de-ad53-11e5-8e20-461441482626.jpg)

![2015-12-28_10-19-01](https://cloud.githubusercontent.com/assets/6084576/12013918/99e81c24-ad53-11e5-8a28-8a23a0deae87.jpg)

Please tell me solve a problem
source code : https://github.com/playcodebyflapjack/bugbootstrapdialog

**Comment by vibintv** [comment]
I am also having the same problem. See this jsfiddle fork http://jsfiddle.net/pwtosqcy/2/ . When removing the tabindex it works fine in google chrome. However removing tabindex in firefox results in misalignment of select. Thank You.

**Comment by nakupanda** [comment]
For now please try setting tabindex of bootstrap-dialog to null to circumvent this issue.
````
BootstrapDialog.show({
    title: '...',
    tabindex: null
});
````

I haven't found out why there is such problem on using BootstrapDialog and Select2 together.

**Comment by nakupanda** [comment]
See a fork of your previous jsfiddle: http://jsfiddle.net/nkpdkdoj/1/

**Comment by nakupanda** [comment]
I believe this has solved the issue, closing it.

**Comment by tfiersen** [comment]
I'm still/again seeing this issue, however only in Firefox (tested with 47.0.1 and 49.0a2 (2016-07-18)), and only when the dialogs height causes scrollbars to appear, see this updated fiddle with a very tall dialog: http://jsfiddle.net/nkpdkdoj/2

**Comment by irdtec** [comment]
A workaround (at least for me), was to set the max-height & overfloy-y css properties on the modal-body; I got the hint from [http://stackoverflow.com/a/18487440](url), in addition to removing the tabIndex from the modal window. Nevertheless, a solution would be appreciated.

Regards.
