### ISSUE TITLE
Cannot close alert box with 1.34.8

### ISSUE THREAD

**Issue by anjos** [nakupanda/bootstrap3-dialog#221]
For some reason, since this release 5 days ago, my alert boxes are not closeable any longer. They will pop-up and won't be dismissible again. Any clues on what would be causing this?

If I install and use version 1.34.6 or 1.34.7, then the alert boxes start to work again as before.

**Comment by ale1981** [comment]
I have the same problem, for the dialog to close I have to force the dialog to close using dialog.close()

This didn't happen in previous versions.

**Comment by anjos** [comment]
After some testing, I can rule out 1.34.7. It seems the issue appears only with 1.34.8. So, it is a recent change.

**Comment by ale1981** [comment]
Agree, I just reverted to 1.34.7 and they work as expected.

**Comment by nakupanda** [comment]
Sorry for the trouble.. Looking into it now.

**Comment by nakupanda** [comment]
Patched, please see if v1.34.9 has solved the problem.

And again thanks for reporting this quickly and sorry for the trouble.

**Comment by nasr18** [comment]
Is there anyway to auto close the bootstrap3 dialog???? I wanna show information like "Saved Successfully" or "Please verify your data" like this. Is there any way to do this???

**Comment by nakupanda** [comment]
@nasr18 , showing message in that way sounds not difficult at all, but what about the next step you expected it would do ?

**Comment by nasr18** [comment]
i want it close after few seconds like alert instead of clicking any where on screen or pressing Esc key. @nakupanda

**Comment by nakupanda** [comment]
Although it's another matter regarding this issue, here is how you can achieve:
````
BootstrapDialog.alert({
	type: BootstrapDialog.TYPE_SUCCESS,
	title: 'Congratulations',
  message: 'Saved Successfully'
}).onShown(function(dialog) {
	setTimeout(function() {
 		dialog.close();
  }, 2000);
});
````
The jsfiddle http://jsfiddle.net/xvtekhv4/3/

**Comment by nasr18** [comment]
awesome bro. Thank you. and very neat ui.  @nakupanda

**Comment by nasr18** [comment]
@nakupanda  what's the difference between BootstrapDialog.alert(), BootstrapDialog.show() and BootstrapDialog.open() . can you please explain it shortly?

**Comment by ale1981** [comment]
@nakupanda  The bug seems to have been solved but not in all dialogs, the problem for me still exists in the confirm dialog.

**Comment by nakupanda** [comment]
@ale1981 , please fork this http://jsfiddle.net/3c03mckb/1/ to reproduce the problem, thanks.

**Comment by ale1981** [comment]
@nakupanda I have edited the fiddle, if you use return false; in the callback the dialog no longer closes, this wasn't the case in 1.34.7, like;

http://jsfiddle.net/ale1981/hor1wwyy/

**Comment by anjos** [comment]
I confirm 1.34.9 works as it used to be before 1.34.8. Thanks for the patch.

**Comment by nakupanda** [comment]
@ale1981 , that's a new feature that introduced in the buggy version 1.34.8 , by returning false in the callback the dialog won't close until you explicitly call dialog.close()

**Comment by nakupanda** [comment]
Please see this https://github.com/nakupanda/bootstrap3-dialog/issues/210

**Comment by ale1981** [comment]
@nakupanda OK, thanks, I have altered my code slightly to solve this, everything else works as expected.

**Comment by nakupanda** [comment]
Good to hear that @ale1981 :)

**Comment by nakupanda** [comment]
@anjos , no problem.
