### ISSUE TITLE
CKEditor and enforceFocus

### ISSUE THREAD

**Issue by glenstephens** [nakupanda/bootstrap3-dialog#222]
I am attempting to use CKEditor in dialogs generated by bootstrap3-dialog.  It currently does not work properly in any bootstrap dialog.  The following code fixes it when used in a statically coded bootstrap modal but not yours:
```javascript
$.fn.modal.Constructor.prototype.enforceFocus = function () {
    modal_this = this
    $(document).on('focusin.modal', function (e) {
        if (modal_this.$element[0] !== e.target && !modal_this.$element.has(e.target).length
        // add whatever conditions you need here:
        &&
        !$(e.target.parentNode).hasClass('cke_dialog_ui_input_select') && !$(e.target.parentNode).hasClass('cke_dialog_ui_input_text')) {
            modal_this.$element.focus()
        }
    })
};
```
Is there anyway something like this can be supported?  Thanks in advance!

**Comment by nakupanda** [comment]
Hi @glenstephens ,

Please create a live demo here http://jsfiddle.net/3c03mckb/1/

**Comment by nakupanda** [comment]
See also http://jsfiddle.net/3c03mckb/6/

The code should look clean and neat enough:

````
BootstrapDialog.show({
	message: function(dialog) {
  	var $editor = $('<textarea/>');
    CKEDITOR.replace($editor[0]);
    
    return $editor;
  }
});
````

**Comment by glenstephens** [comment]
Here is the fiddle that shows the issue:
http://jsfiddle.net/3c03mckb/8/

Let me know if you need any other information.  If you need it, this fiddle shows the enforceFocus working properly on the traditional bootstrap dialog.  ( http://jsfiddle.net/pvkovalev/4PACy/ )

**Comment by nakupanda** [comment]
It seems you are looking for a way to focus on the editor after it's initialized, if this is right, see here http://jsfiddle.net/vpwjyg7t/1/

**Comment by glenstephens** [comment]
@nakupanda, not quite. Here is what is not working.
![example](https://cloud.githubusercontent.com/assets/5613889/12438001/1fe809e0-bee0-11e5-93a7-96bdb31eff5e.jpg)

**Comment by nakupanda** [comment]
Try this
http://jsfiddle.net/67k2tkp6/1/

But I don't exactly know why tabindex does the trick.

**Comment by glenstephens** [comment]
That did the trick!! Thanks so much!

**Comment by nakupanda** [comment]
No problem, and sorry for the trouble.

**Comment by glenstephens** [comment]
Thanks for the prompt replies! Great plugin!

**Comment by nakupanda** [comment]
You're welcome :)

Your jsfiddles and images described the issue well.

**Comment by waspinator** [comment]
This fix seems to work great for Chrome, Safari, IE11, and Edge, but **not** in Firefox (46).

**Comment by munkh-altai** [comment]
@nakupanda 
Thank you very much. saved my day

**Comment by joshbmarshall** [comment]
Your solution to #238 seems to be on the mark for Firefox (yes I know this is a long time later but still had the issue where chrome was working).
I have a system where I have one function called repeatedly to create the ckeditor and many places where bootstrap dialogs are opened so I tweaked the jsfiddle a little to make it work nicely. Sharing it for anyone coming across this! https://jsfiddle.net/gn9p0zbe/
