### ISSUE TITLE
Bootstrap 4 

### ISSUE THREAD

**Issue by Izopi4a** [nakupanda/bootstrap3-dialog#225]
I know its alpha and so on..., but  i don't have enough time atm to check it but I get this error:

`Uncaught TypeError: Cannot call a class as a function`

is it something possible to be fixed without screwing everything else ?

**Comment by nakupanda** [comment]
Are you using bs4?

**Comment by Izopi4a** [comment]
yes

**Comment by nakupanda** [comment]
It does not support BS4 so far, but we will step into it soon.

**Comment by Izopi4a** [comment]
ok thx.

**Comment by rternier** [comment]
Any word on a Bootstrap 4 version?

**Comment by nakupanda** [comment]
No so far :)

**Comment by GESHIRO** [comment]
when will it be ready for bs4?

**Comment by D-Skywalker** [comment]
This merge helped me,  maybe help you too:

https://github.com/avan06/bootstrap3-dialog/blob/7a6ce48fe0df38847fe413765cac9dce203b6510/src/js/bootstrap-dialog.js

**Comment by tmaly1980** [comment]
FYI, 4.0.0-beta.2 is out
