### ISSUE TITLE
I suggest that in the "BootstrapDialog.confirm ()" method, should swap "OK" and "Cacel" buttons's position

### ISSUE THREAD

**Issue by hldgaofeng** [nakupanda/bootstrap3-dialog#231]
I suggest that in the "BootstrapDialog.confirm ()" method, should swap "OK" and "Cacel" buttons's position, just like the "window.confirm" in the browser.

**Comment by nakupanda** [comment]
It's a iOS convention, however it seems adding a new feature to optionally choose what order to use on buttons is a good choice too.

**Comment by hldgaofeng** [comment]
Or may be it can detect OS type to adjust button position automatically.
```javascript
if( windows ) {
   // ok then cancel ...
} else if( iOs ) {
   // cancel then ok ...
} else {
 //...
}
```

**Comment by nakupanda** [comment]
We can do that, but it should be decided by the developer.

**Comment by darrensw777** [comment]
+1 for this

**Comment by nakupanda** [comment]
Please see the last comment in this issue #144 (comment)
