### ISSUE TITLE
Document nl2br

### ISSUE THREAD

**Issue by stanvass** [nakupanda/bootstrap3-dialog#233]
Hi, I see this issue keeps coming up, people are surprised by the default behavior of replacing new lines with \<br\> tags. I was surprised by it, as well.

Even worse, the nl2br option is not documented here: https://nakupanda.github.io/bootstrap3-dialog/ so I had to go digging into the source code to find it.

Can I please suggest:

1. This option should be off by default, or...
2. At least it should be very clearly documented on the main project page so people can CTRL+F that page and find matches for "new lines" or similar, pointing them to set nl2br to false.

Thanks!

**Comment by nakupanda** [comment]
You're right, especially for 2), gotta change it soon but one thing that I'm worrying about is that, who used to use nl2br: true would have troubles after updating bootstrap3-dialog.

**Comment by nakupanda** [comment]
Please see this commit https://github.com/nakupanda/bootstrap3-dialog/commit/6b523d96acbd199ad20f78cdd57bf812e9ec81f2

**Comment by MichaelSagalovich** [comment]
Just as mentioned above, everyone knowing about this property and relying on it being true by default will have their code broken. Why not have it still true, just well documented? Who needs it false will explicitly define it, but we will keep backward compatibility - is not it important?

**Comment by nakupanda** [comment]
@MichaelSagalovich , we still have time to change it (true or false by default) before a new release is published.

Per your comment, and mine as well, leaving it as false by default as it was sounds more reasonable.

+1 for default nl2br: false

**Comment by MichaelSagalovich** [comment]
Yeah, that's why I was pretty surprised when I saw the commit with true :)

**Comment by nakupanda** [comment]
Ok, it's true by default again, and it's also documented in example page.
