### ISSUE TITLE
CKEditor IE: Drop-downs closed immediately after show

### ISSUE THREAD

**Issue by CallMeBruce** [nakupanda/bootstrap3-dialog#238]
Hi,

When using CKEditor within a bootstrap3-dialog on IE, dropdowns (font, paragraph etc) show and immediately close. CKEditor ticket http://dev.ckeditor.com/ticket/12525 describes the issue and proposes a solution. 

That solution doesn't work for bootstrap3-dialog unfortunately, I found https://github.com/nakupanda/bootstrap3-dialog/issues/222 which references http://jsfiddle.net/67k2tkp6/1/ and whilst it does fix the focus issue, if you test in IE you will see the same issue with the Styles or Paragraph dropdowns (they show and close immediately).

Would you have any idea how I can resolve this for IE? Thanks in advance.

**Comment by nakupanda** [comment]
Tried something but they didn't work, will keep looking for a solution, sorry for the trouble.

**Comment by nakupanda** [comment]
Please see http://jsfiddle.net/ewyp7azo/2/

**Comment by CallMeBruce** [comment]
Thanks but not quite working, your fiddle does work but only because it crashes the JS (which causes the call to .focus() to fail always), when I run the fiddle i get a script debug popup "Line: 51
Error: '$modalElement' is undefined"

**Comment by CallMeBruce** [comment]
Ok, so I have tracked down why my attempts are failing, it seems that the solution, to override the default behaviour of enforceFocus for the contructor of the modal object, fails to override.

i.e.

the bootstrap.js file contains this

```javascript
  Modal.prototype.enforceFocus = function () {
    $(document)
      .off('focusin.bs.modal') // guard against infinite focus loop
      .on('focusin.bs.modal', $.proxy(function (e) {
        if (this.$element[0] !== e.target && !this.$element.has(e.target).length) {
          //this.$element.focus()
        }
      }, this))
  }
```

and to resolve the issue I should use something like this after jquery and bootstrap are loaded,

```javascript
$.fn.modal.Constructor.prototype.enforceFocus = function () {
    var $modalElement = this.$element;
    $(document).on('focusin.modal', function (e) {
        var $parent = $(e.target.parentNode);
        if ($modalElement[0] !== e.target
                        && !$modalElement.has(e.target).length
                        && $(e.target).parentsUntil('*[role="dialog"]').length === 0) {
            $modalElement.focus();
        }
    });
};
```
which, if it were invoked, would indeed resolve the issue. But, if i debug the code, it isn't called, the original bootstrap one is still called. 

I know that this has nothing to do with your excellent plugin, but hoping that you can help me see what I am missing and why the method isn't overwritten.

**Comment by nakupanda** [comment]
Sorry for the silly mistake, I didn't check the console. 

See  http://jsfiddle.net/e2qeaz59/1/

I just found a place to put the 'enforceFocus' in position for BootstrapDialog, not sure if there will be other problems.

**Comment by CallMeBruce** [comment]
Absolute legend! :+1: works like a charm. I'm guessing that the prototype override failed because of the instantiation of the plugin per usage, does that sound right to you?

Regardless, thanks very much for helping solve this issue, really didn't want to hack the bootstrap.js files!

**Comment by nakupanda** [comment]
No problem :)

And about your guess - not quite right here, but you were right when you mentioned 

> if it were invoked, would indeed resolve the issue

, it actually won't be invoked within the plugin.
