### ISSUE TITLE
setMessage destroys DOM element even though autodestroy=false

### ISSUE THREAD

**Issue by developerdu** [nakupanda/bootstrap3-dialog#242]
Hi,

I have a scenario similar to issue #162 - and I worked out that by setting autodestroy to false the DOM element would not be destroyed and so a second launch of the dialog would work.

However, I have since made the dialog look like it has two pages - on pressing a "next" button, I call dialog.setMessage with a different DOM element to show a different "page".  And it seems that this call destroys the original DOM element and again the dialog displays empty on a second launch even with autodestroy set to false.

Any suggestions?

Thanks.

**Comment by nakupanda** [comment]
I guess the element was destroyed because when calling dialog.setMessage to show another page the first was wiped, and when you try to show the first again it's no longer available.

There are many solutions but they depend on your needed, if preserving data is not a necessary, you may use $element.clone() as the message to show.

````
BootstrapDialog.show({
      message: $('#page-one-or-page-two').clone()
});
````
Or
````
dialog.setMessage($('#page-one-or-page-two').clone());
````

This won't break anything but the cons is that each time you open the dialog it's a fresh page.

Or if preserving data or status between pages is required, you will need to keep it in some ways, an example is as below:

````
var pageOne = $('#form-one');
var pageTwo = $('#form-two');

dialog.setMessage(pageOne);
dialog.setMessage(pageTwo);
dialog.setMessage(pageOne);
dialog.setMessage(pageTwo);
````

The best is to create an online demo thus I can clearly see your problem and fork to give a solution if possible.

**Comment by developerdu** [comment]
Thanks for your fast response.  Unfortunately neither approach seems to work for my situation.  clone just resulted in a blank screen from the first launch and the second method shows my table, but all the code set up to handle clicks on the table don't work.

I have a workaround which is recreating the DOM elements by hand if they don't exist but it is a bit of a pain to have to do.

I will try and create an online demo when I have a bit more time.

**Comment by developerdu** [comment]
I've put up a demo here https://jsfiddle.net/developerdu/5bvmyujx/

**Comment by nakupanda** [comment]
I forked your demo and modified to have this one https://jsfiddle.net/e4s2vrm3/1/

Which is the solution I mentioned above, hope that's what you were looking for.

And I have also removed some lines to make it clean, and to hide the two pages in the original page I also added a outer container and set it as hidden, this does the trick showing the two pages in the dialog only but in original page they're hidden.

**Comment by nakupanda** [comment]
I'm sorry, I forgot to modify the table events in above demo, please see this one https://jsfiddle.net/e4s2vrm3/2/

**Comment by developerdu** [comment]
I just tested https://jsfiddle.net/e4s2vrm3/2/ and the first table still doesn't respond to a mouse click when the dialog is launched a second time?

**Comment by nakupanda** [comment]
How about this https://jsfiddle.net/74qzdmq6/1/ ?

**Comment by nakupanda** [comment]
Or try this solution https://jsfiddle.net/rry4sqea/1/

Note that I removed autodestroy: false as you have put dialog creation inside the button event handler, each time you click the button a new dialog will be created which means it does not make sense setting it to false.

**Comment by developerdu** [comment]
Thanks for the help with the workaround.  That last solution works as it should and is more elegant than the hack that I came up with for myself!

**Comment by nakupanda** [comment]
No problem :)
