### ISSUE TITLE
less files not copied to dist in bower

### ISSUE THREAD

**Issue by tl24** [nakupanda/bootstrap3-dialog#243]
We use bootstrap3-dialog via bower.  It looks like with the latest release, the less files are no longer in the dist directory.  The less file is referenced in bower.json there.  Need to either put the code back to copying less file from src to dist, or update the bower.json.  We use npm main-bower-files in our build for js and less building/minification.

**Comment by nakupanda** [comment]
I put the file back into dist/less, thanks for the finding.

**Comment by nakupanda** [comment]
Changes are here https://github.com/nakupanda/bootstrap3-dialog/commit/fdd7b480aaddf7ba1c6438598e3e62eda68e54b9
