### ISSUE TITLE
Returning false in onshow twice causes error 

### ISSUE THREAD

**Issue by dillchuk** [nakupanda/bootstrap3-dialog#248]
```
        for (i = 0; i < 2; i++) {
            BootstrapDialog.show({
                onshow: function () {
                    return false;
                }
            });
        }
```
on the 2nd iteration yields `Uncaught TypeError: Cannot read property 'css' of null`.

**Comment by dillchuk** [comment]
My intent is to use `onshow` to prevent dialog on certain conditions.  For now, I just wrap with a try/catch.

**Comment by nakupanda** [comment]
Looking into it..

**Comment by nakupanda** [comment]
I confirmed it's my mistake.

Thanks for this finding :+1:

**Comment by nakupanda** [comment]
It's fixed, get the patched version here https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.35.0
