### ISSUE TITLE
NPM Module needs to point at dist, not src.

### ISSUE THREAD

**Issue by baconface** [nakupanda/bootstrap3-dialog#249]
Currently the package on NPM is 1.34.6. So maybe it has been fixed since then and not pushed. But the current version offered is affected by this.

My issue is my Gruntfile.js purposely removes the src from my project's root and it's dependencies. This is so my final release is a little lighter. Being an Electron application I can use all the trimming I can get. It appears the Node module uses the src instead of the dist for the bootstrap-dialog.js. As a result it gets stripped from my production build and breaks my application. Of course I can mess around with my Gruntfile.js and get around this. But I would prefer to not use/ship the src at all since a dist is offered.

Thanks.

**Comment by nakupanda** [comment]
My apologies, I missed this issue.

Have you got a solution for this and can be merged into master branch of the library ?

**Comment by baconface** [comment]
When looking at the source I noticed `main` is not set at all in package.json. So is this set by a build script somewhere? I couldn't see an obvious mentioned in the Gulp file. But I am a Grunt user so maybe it is but I just don't see it.

Additionally I noticed master branch is at version 1.35.1 whereas the NPM latest release is 1.34.6.

This is what my package.json looks like from the NPM release. It is significantly different than the one I found in the repo.
```json
{
  "name": "bootstrap-dialog",
  "version": "1.34.6",
  "description": "Make use of Bootstrap Modal more monkey-friendly.",
  "directories": {
    "example": "examples"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/nakupanda/bootstrap3-dialog.git"
  },
  "keywords": [
    "bootstrap",
    "dialog"
  ],
  "author": {
    "name": "nakupanda"
  },
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/nakupanda/bootstrap3-dialog/issues"
  },
  "homepage": "http://nakupanda.github.io/bootstrap3-dialog",
  "main": "src/js/bootstrap-dialog.js",
  "devDependencies": {
    "eslint": ">=0.6.2",
    "gulp": ">=3.8.1",
    "gulp-clean": ">=0.3.0",
    "gulp-eslint": ">=0.1.7",
    "gulp-less": ">=1.2.3",
    "gulp-minify-css": "^0.3.4",
    "gulp-notify": ">=1.3.1",
    "gulp-rename": ">=1.2.0",
    "gulp-streamify": "0.0.5",
    "gulp-uglify": ">=0.3.0",
    "vinyl-source-stream": "^0.1.1"
  },
  "gitHead": "2af02f16dd1c912a0b1a4388cb8caf8c811b41a0",
  "_id": "bootstrap-dialog@1.34.6",
  "_shasum": "6e5e15a4dc8e0a8ae0c539a50d00628a8da65f0b",
  "_from": "bootstrap-dialog@>=1.34.6 <2.0.0",
  "_npmVersion": "2.13.3",
  "_nodeVersion": "2.3.4",
  "_npmUser": {
    "name": "bgdavidx",
    "email": "david@chatous.com"
  },
  "dist": {
    "shasum": "6e5e15a4dc8e0a8ae0c539a50d00628a8da65f0b",
    "tarball": "http://registry.npmjs.org/bootstrap-dialog/-/bootstrap-dialog-1.34.6.tgz"
  },
  "maintainers": [
    {
      "name": "bgdavidx",
      "email": "david@chatous.com"
    }
  ],
  "_resolved": "https://registry.npmjs.org/bootstrap-dialog/-/bootstrap-dialog-1.34.6.tgz",
  "readme": "ERROR: No README data found!"
}
```

**Comment by nakupanda** [comment]
See #256 for the old NPM package problem

**Comment by baconface** [comment]
Ah, wonderful. Always fun when multiple repos are up for the same project that cause confusion.

I will use this repo when I get to work today and see if this issue still exists. Thanks for the heads up.

**Comment by baconface** [comment]
So after changing to the official package and setting the `main` I seem to be having an issue with the exports. It fails to work for my application.

Changing:
```javascript
    if (typeof module !== 'undefined' && module.exports) {
        var isNode = (typeof process === "object") && (typeof process.versions === "object");
        var isElectron = isNode && ('electron' in process.versions);
        if (isElectron) {
            root.BootstrapDialog = factory(root.jQuery);
        } else {
            module.exports = factory(require('jquery'), require('bootstrap'));
        }
    }
```
To:
```javascript
    if (typeof module !== 'undefined' && module.exports) {
            module.exports = factory(require('jquery'), require('bootstrap'));
    }
```
Makes it work for me.

Why is all the Electron conditional code involved? The module should work without since it is loaded in the Node.js context using `require`. If they wish to include it using script tags this should be managed via the `nodeIntegration` and not via the exports.

**Comment by baconface** [comment]
I can make a PR that does all this properly. But it will break for people that use `nodeIntegration` set to true and are including it via script tags. However, they are using it the wrong way. In Electron it should be imported via `require` and use NPM style module exports. Which is the way we the other package works and the way we need it to work in our project as well.

**Comment by nakupanda** [comment]
Thanks for your efforts, @baconface 

We need more discussions as I'm not familiar with this.

@bitclaw 
@levacic 
@AndrewEastwood 
@codepiano

**Comment by baconface** [comment]
No problem. And for reference [here is a similar issue](https://github.com/electron/electron/issues/254) that was brought up about jQuery. Here it was clarified how Electron expects packages to be loaded as if it were in the CommonJS environment. To me, it just doesn't make since to use all packages with exports one way and then the `bootstrap3-dialog` a completely different way.

https://github.com/electron/electron/issues/254

**Comment by codepiano** [comment]
I load jquery via `<script>window.$ = window.jQuery = require('jquery');</script>`, but bootstrap-dialog will set BootstrapDialog object to window.module.exports instead of window, so I add these code to make it work.
Hope you can fix this graceful.

**Comment by baconface** [comment]
Hoping this adds a little clarity. If you do it the regular CommonJS environment way this should work.
```javascript
window.$ = window.jQuery = require('jquery');
const BootstrapDialog = require('bootstrap3-dialog');
```
No additional Electron code needing to be in the bootstrap-dialog.js By adding such you are changing how the package should be used in it's expected environment makes this works against the grain. As a result I cannot require BootstrapDialog. Not everyone wants to use script tags in the DOM.

@codepiano Can you try to changing your CommonJS module condition to the following and see if this works for you? If so this might be a solution for both of us.
```javascript
    if (typeof module !== 'undefined' && module.exports) {
        var isNode = (typeof process === "object") && (typeof process.versions === "object");
        var isElectron = isNode && ('electron' in process.versions);
        if (isElectron) {
            module.exports = factory(window.$ = window.jQuery = require('jquery'), require('bootstrap'));
        } else {
            module.exports = factory(require('jquery'), require('bootstrap'));
        }
    }
```

I am not fond of this way completely. But at least this way if you load it in as `const BootstrapDialog = require('bootstrap3-dialog');` it should load in jQuery and Bootstrap as well and hopefully still work with loading it in via the script tags. This also works for me in addition to assigning the dist script in the package.json.

You will just need to remove your require for jQuery in your code as it is no longer needed. But a quick test has shown it didn't appear to conflict meaning it should still be graceful.

**Comment by baconface** [comment]
The biggest con with the above is people will need to know to `require` bootstrap3-dialog before any other jQuery dependent package. This is why I am still in favor of:
```javascript
    if (typeof module !== 'undefined' && module.exports) {
        module.exports = factory(require('jquery'), require('bootstrap'));
    }
```
And loading it in via when using Electron:
```javascript
window.$ = window.jQuery = require('jquery');
const BootstrapDialog = require('bootstrap3-dialog');
```
That is how all other packages handle this.

**Comment by baconface** [comment]
In the meantime we are just loading a fork with our fixes via NPM.

**Comment by codepiano** [comment]
I use regular CommonJS environment way, it works for me, so there's no need to add these Electron conditional code, you can send a pr to delete it, thanks.
I use script tag to load bootstrap3-dialog and jquery before, it's not the proper way.
Appreciate for your patience and explanation.

**Comment by baconface** [comment]
Thanks @codepiano. :+1: 

I have submitted a PR with the explanation of what it's purpose is. Once accepted this should close the issue.

https://github.com/nakupanda/bootstrap3-dialog/pull/277

**Comment by nakupanda** [comment]
Done merging, thanks for all your efforts!

**Comment by nakupanda** [comment]
@baconface 

You can close this issue after reviewing everything.

**Comment by baconface** [comment]
Aside from the NPM package not yet using this version I have verified that everything works on my end. Thanks everyone.

**Comment by levacic** [comment]
@nakupanda You should tag and publish a new release. Instructions for updating the npm package are [here](https://github.com/nakupanda/bootstrap3-dialog/issues/256#issuecomment-219061771), I can also do that if you wish as soon as you tag a new version (it also needs to be updated in `package.json`).

**Comment by nakupanda** [comment]
You're right, @levacic , and it's here https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.35.2

**Comment by levacic** [comment]
Thanks, it's published now: https://www.npmjs.com/package/bootstrap3-dialog

**Comment by nakupanda** [comment]
Thanks :)
