### ISSUE TITLE
BootStrapDialog not working properly inside click handler

### ISSUE THREAD

**Issue by geromemuent** [nakupanda/bootstrap3-dialog#250]
Hi together

When I'm using BootStrap.alert in that way:
$(document).ready(function() {
BootstrapDialog.alert('I want banana!');

...
}
everything behaves like expected. The dialog appears modal, I have to close it and then all the rest of the page is accessible again.

But when I do it the following way:
$(document).ready(function() {

$('#loginButton').on('click', function() {
BootstrapDialog.alert('I want banana!');

}
...
}

the dialog appears, but does not wait for closing it and closes itself immediately. Why?
It must be a problem of the context.
Can you help?

Thx for help, regards, Bernd

**Comment by nakupanda** [comment]
Hi,

Within only the codes you provided, it works, please see http://jsfiddle.net/n8j1od0a/1/

**Comment by geromemuent** [comment]
Thx for having a look!
I found out, that the problem is a surrounding <form>...</form>.
With <form onsubmit="return false;"> everything works fine. I never have to send the form itself. The values are submitted via AJAX-Request.
Regards, Bernd

**Comment by nakupanda** [comment]
No problem :)
