### ISSUE TITLE
Empty dialog DOM exists after closing the dialog with `autodestroy=false`

### ISSUE THREAD

**Issue by zhang-yuan** [nakupanda/bootstrap3-dialog#254]
Hi,

I want to konw how to clean these unuseful empty model doms, I set `autodestroy=false` in my dialog and I expected to pop up and down the dialog again and again but without adding more and more empty DOM to my page. (atteched is my log)

Is there any solution for this?
Thanks!

![2016-03-31_164205](https://cloud.githubusercontent.com/assets/9049007/14170461/76d24fb4-f760-11e5-8436-e26368802b5a.png)

**Comment by nakupanda** [comment]
So why don't you set autodestroy = true?

**Comment by zhang-yuan** [comment]
Problem solved, and sorry for the delay.

By reading your doc carefully, I found it's the same situation as #204 .(yes, I was not using the same instance...)
Sorry about that :laughing:

**Comment by nakupanda** [comment]
no problem :)
