### ISSUE TITLE
ckeditor dialog options broken inside bootstrap modal

### ISSUE THREAD

**Issue by waspinator** [nakupanda/bootstrap3-dialog#263]
Hi,
I'm trying to embed a ckeditor inside a bootstrap dialog, but ckeditor's own modal options become broken. Any ideas if this can be fixed from the bootstrap-dialog side?

Thanks for the great library.

https://jsfiddle.net/waspinator/10om09rk/

![Image of Yaktocat](http://i.stack.imgur.com/vInK9.gif)

**Comment by nakupanda** [comment]
Hi,

Haven't looked into it yet but please see this issue https://github.com/nakupanda/bootstrap3-dialog/issues/222

**Comment by waspinator** [comment]
Thanks for that link. It seems to fix the issue for most browsers, but not Firefox...

**Comment by waspinator** [comment]
I've given up on CKeditor for now and switched to TinyMCE.

**Comment by pudjamansyurin** [comment]
@nakupanda the question is about Bootstrap Modal, but you reference to Bootstrap Dialog discussion.

**Comment by pudjamansyurin** [comment]
For me, the solution is on my modal attribute initialization, 

`		<div class="modal fade" id="lokerModal" tabindex="-1" role="dialog">
			<div class="modal-dialog modal-lg" role="document">
				<div class="modal-content">`

Just remove `tabindex="-1"` and everything works well, thanks

**Comment by technologiesorion** [comment]
@pudjamansyurin excellent 🥇 ! best solution for every bootstrap or jquery ui version... and so easy.

**Comment by merkancam** [comment]
> I've given up on CKeditor for now and switched to TinyMCE.

thx man. I was having many troubles with ckeditor. I did what i wanted with TinyMCE which has a good documentation.

**Comment by coda-apps** [comment]
@pudjamansyurin  - correct solution - thanks!
