### ISSUE TITLE
Hotkey for confirm dialog

### ISSUE THREAD

**Issue by amirkhiz** [nakupanda/bootstrap3-dialog#271]
It's just a suggestion; I think if it is possible to add hotkey option for confirm dialog. I think there is no way to do that.
And thank you for your great plugin. ;)

**Comment by nakupanda** [comment]
That's a good idea, and the pull request looks good too. But there seems to be too many changes that made from reformatting the source js file, how about to just submit a pull request with only necessary changes?

**Comment by nakupanda** [comment]
BTW your reformatted file looks better, what tool / ide do you use ?

**Comment by amirkhiz** [comment]
Thank you, the changes as you said because of my IDE reformat.
I use PHPStorm and i am very pleased that, It's really awesome.

**Comment by amirkhiz** [comment]
_**how about to just submit a pull request with only necessary changes?**_
Of course after commit i saw the reformat changes. I will send you new pull request with just necessary changes.

**Comment by nakupanda** [comment]
OK thank you :)

**Comment by Codepadawan** [comment]
So, the pull request got closed, and this issue never got resolved? I would really like to see this change.

**Comment by nakupanda** [comment]
Waiting for another pull request.

**Comment by Codepadawan** [comment]
I gather the pull request provided by @amirkhiz had too many unnecessary changes, which made being comfortable with it difficult - would you like me to make a new one with just the necessary changes?

**Comment by nakupanda** [comment]
We'd better wait for @amirkhiz feedback first.

**Comment by amirkhiz** [comment]
I'm really sorry for my late to complete this issue today i'll complete this. ;)
Thanks for your patient.

**Comment by nakupanda** [comment]
Guys,

It's included in the latest release https://github.com/nakupanda/bootstrap3-dialog/releases/tag/v1.35.3

**Comment by nakupanda** [comment]
Thanks for @amirkhiz great works!

**Comment by amirkhiz** [comment]
Thank you for merging @nakupanda. Good luck
