### ISSUE TITLE
How do we get the instance of an opened dialog ?

### ISSUE THREAD

**Issue by Ready4Next** [nakupanda/bootstrap3-dialog#275]
Hi,

Is there a way to get the instance of an opened dialog by an element id from jQuery ?

Something like this: 

```
// We open a dialog somewhere and get it's element id...
var dialogId = bootstrapDialog.getModal().attr('id');

// And in another place, we try to get the dialog to close it
var dialog = $('#" + dialogId).instance('BootstrapDialog');
dialog.close();
```

Thanks

**Comment by webprogramozo** [comment]
You can retrieve the bootstrap3-dialog instance by calling the following code:
`var instance = $("selector-to-your-modal").data("bs.modal");`

**Comment by Ready4Next** [comment]
Many thanks @webprogramozo, this is all I need :).

**Comment by webprogramozo** [comment]
You're welcome! :)
