### ISSUE TITLE
Switch order of confirmation dialog

### ISSUE THREAD

**Issue by Xirt** [nakupanda/bootstrap3-dialog#284]
I noticed that the confirmation dialog currently first shows the "Cancel"-button (left) and next to it the "Ok"-button (right). Many systems (I agree not all) have them reversed showing first the "Ok"-button and then the "Cancel"-button. Would it be possible to add a switch-parameter to the method for this?

**Comment by nakupanda** [comment]
Please see the last comment in this issue https://github.com/nakupanda/bootstrap3-dialog/issues/144#issuecomment-239164117
