### ISSUE TITLE
Is this a drop-in replacement?

### ISSUE THREAD

**Issue by EugenMayer** [nakupanda/bootstrap3-dialog#286]
i am sorry to ask here, but i looked at the examples, looked at the docs and kind seem to grasp, that bootstrap-dialog is not a drop-in replacement for the bootstrap dialogs?

I ask this in particular since we already use a log of bootstrap dialogs using the bootstrap api, i need modal-stacking as a feature there, and so on. Iam happy to spawn new dialogs using the simplified api, but still, i expected bootstrap-modal to replace or enrich the current implementation.

Looking at the way its integrated with "overrides" it actually sounds like it is a drop-in replacement.

Could you clarify on this? Thanks!

**Comment by EugenMayer** [comment]
I guess, the overrides defined are rather to change the behaviour of bootstrap3-dialog in regard of the bootstrap version.

Looking at the code, i hardly see any integration points with the bootstrap modal api, right?

So basically bootstrap3-dialog is rather a standalone dialog system reusing bootstraps dialog styling, overriding some of those and "kinda" uses the backdrop as an 'api' 

but thats basically it, right?

**Comment by EugenMayer** [comment]
Oh, the dialog itself uses exactly the same html markup. Since we define a lof of dialogs backend-side and return them "pre-rendered" into the gui to be able to pop them up pretty fast, thats a desired feature for us.

Probably, AFAIC, when i have the needs to shop up a prerendered modal, i would implement a wrapper based on this, probably inserting body / header and things using the methods.

**Comment by EugenMayer** [comment]
After playing arround a bit, it would be fairly simple to have a basic override of the current modal implementation

http://jsfiddle.net/o5k0eaws/215/

bootstrap-dialog is really well written, thank you for this very interesting library. A lot of layers, a lot of ways to change the way things do get invoked. Nice architecture.

**Comment by EugenMayer** [comment]
Also created the same with bootstrap4 as the base, works pretty well http://jsfiddle.net/o5k0eaws/217/

**Comment by nakupanda** [comment]
I'm happy you have finally found your way. Yes bootstrap-dialog is just a tool that makes using bootstrap modal easier, doesn't mean it's another modal at all.

Most APIs were designed to be able to be reused and overridden, in most cases people can do their works without modifying anything inside the library.

**Comment by nakupanda** [comment]
If your problem have got solved, I'd like to close this issue.

**Comment by nakupanda** [comment]
Your jsfiddle works imperfectly, however bootstrap-dialog utilizes exact the bootstrap modal and have it a little bit modified on appearances like header color, close button, etc. I think you will find another better way to achieve your goal.

**Comment by EugenMayer** [comment]
@nakupanda yes as outlined in http://jsfiddle.net/o5k0eaws/219/ the modal-backdrop issue resides.. the title and things are actually just markup-example limitations and very easy to fix.

Do you have an idea how i would override modal('show') and modal('hide') in bootstrap4 to use the bootstrap3-dialog approach 

```
var dialog = new BootstrapDialog({          
  closable: false
});
dialog.realize();
dialog.setModal($('#myModal'));    
dialog.open();                
```

Hooking that into bootstrap in general could be a really nice addition to b3-dialog, of course as an opt-in, but this way, you unify all dialogs in the system and enable stacking for every $().modal('show') call in the system, which might exists or is used by a 3rd party lib
