### ISSUE TITLE
Comparison with bootboxjs?

### ISSUE THREAD

**Issue by mizzao** [nakupanda/bootstrap3-dialog#29]
I've been using Bootbox.js (http://bootboxjs.com/) and just happened upon this. It seems to be doing pretty much the same things, except Bootbox has been around much longer and has been supported since earlier versions of Bootstrap (other than 3).

What are the major differences?

Bootbox.js repo: https://github.com/makeusabrew/bootbox

**Comment by domino14** [comment]
what does monkey friendly mean?
