### ISSUE TITLE
animate remote page content once loaded

### ISSUE THREAD

**Issue by waspinator** [nakupanda/bootstrap3-dialog#293]
I'm looking for a way to animate in remote page content once loaded. Right now content pops-in jarringly, and I think it would be nicer to have in slide down and fade in instead.  

Pop-in remote page
https://jsfiddle.net/waspinator/2qd1j3om/

Example of slide down and fade in ajax content
https://jsfiddle.net/waspinator/notp5by5/

Is there some way to combine the two?

**Comment by waspinator** [comment]
I found a way to combine the two. If there's a better way please let me know.

https://jsfiddle.net/g04ou98y/

**Comment by nakupanda** [comment]
The effect looks awesome, learning now..

**Comment by waspinator** [comment]
I'm not sure how it can be done, but maybe it would be nice to have a `animateRemoteMessage` option that would do the animation jquery stuff for you.

**Comment by nakupanda** [comment]
Loading remote page isn't even a supported option of neither bootstrap3-dialog and bootstrap modal, I think we should animate it without modifying internals.

**Comment by nakupanda** [comment]
If you're just looking for 'better' way for doing this, see this fiddle: https://jsfiddle.net/b3zcah5f/1/

You can define a new class for making animation for the dialog when remote page is load. You can place the class into a standalone js file then it should look clean enough and you can reuse it anywhere.

**Comment by waspinator** [comment]
That looks like a great way of doing it, thanks!
