### ISSUE TITLE
BootstrapDialog.confirm ignores options cssClass: and id:

### ISSUE THREAD

**Issue by uvesten** [nakupanda/bootstrap3-dialog#297]
See example here:

http://jsfiddle.net/z7h4c12n/

**Comment by waspinator** [comment]
I don't see any css or id options in your fiddle.

**Comment by uvesten** [comment]
Neither do I when clicking the link now. Sigh

**Comment by waspinator** [comment]
Could you try to fix it to show the problem? Otherwise maybe close the issue for now.

**Comment by nakupanda** [comment]
@uvesten , I understand the problem, I will check current implementation and see how to improve it.

**Comment by nakupanda** [comment]
I labelled this issue an enhancement rather than a bug.

**Comment by nakupanda** [comment]
OK, I got the cause. The id and cssClass options being ignored because you're using old version of the library.

See a updated version: http://jsfiddle.net/42a9cztw/1/

**Comment by nakupanda** [comment]
Making the import statement refers to bootstrap3-dialog v1.35.3 should fix your problem.

**Comment by uvesten** [comment]
Thanks! Sorry for the slow response from my side!
