### ISSUE TITLE
remove default OK button

### ISSUE THREAD

**Issue by leandroruel** [nakupanda/bootstrap3-dialog#309]
i'm creating a new instance of dialog, but when i'm creating that with my custom buttons (yes and no buttons), he keep the default OK button, letting me with 3 buttons - yes - no - OK. so, how i can remove this?

**Comment by nakupanda** [comment]
What are your codes?

**Comment by leandroruel** [comment]
i'm closing this issue because i notice the diference between .show and .alert, and in a .alert i can't remove the button, so i commit a made, after read all the docs i get it
