### ISSUE TITLE
I have html content and I'm getting a bunch of <br> tags in there, what am I missing?

### ISSUE THREAD

**Issue by trainbolt** [nakupanda/bootstrap3-dialog#31]
Is there a setting for html content instead of string? I really don't want to strip the whitespace from my html to get this working.

Thanks.

**Comment by GaikwadPratik** [comment]
@nakupanda 
Hi,
I am still getting the same issue. I have downloaded v1.35.3 from npm. Using `message: $('<div></div>').append(_htmlSource)` solved the issue. I tried setting `nl2br:true` but it didn't work. Let me know if you need more information from my end.

**Comment by GaikwadPratik** [comment]
@nakupanda ,

I'm still getting this error when I am using source from npm package. However if I use CDN the issue is not replicating. Do you have any idea why its behaving like this?

P.S. I was able to solve it by setting `nl2br:false` but shouldn't be default value be `false`?
