### ISSUE TITLE
modal-backdrop cover modal-dialog

### ISSUE THREAD

**Issue by Teaism** [nakupanda/bootstrap3-dialog#311]
hello,
i see  bootstrap-dialog.min  setting div.modal-backdrop   z-index: 1040;
<div class="modal-backdrop fade in" style="z-index: 1040;"></div>
it cover  div.modal-dialog. 
so,Whether should setting  div.modal-dialog. more number z-index.???  i do.
that's me meet.  
sincerely, thanks yours.

**Comment by nakupanda** [comment]
Hi XiaoFang,

Why did you close this issue?
