### ISSUE TITLE
jsdelivr support?

### ISSUE THREAD

**Issue by LeoWinterDE** [nakupanda/bootstrap3-dialog#330]
Hi,
are there any plans to offer the file over [jsdelivr.com](http://www.jsdelivr.com/)? [Guide.](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md ) I would be glad.

**Comment by nakupanda** [comment]
Hi,

Thanks for introducing jsdelivr, learning it. If you are familiar with it, please create a PR. thanks.

**Comment by LeoWinterDE** [comment]
I've managed it get the files up to @jsdelivr
- https://www.jsdelivr.com/?query=bootstrap3-dialog
- https://github.com/jsdelivr/jsdelivr/tree/master/files/bootstrap3-dialog

**Comment by jimaek** [comment]
The new backend is live. It pulls files directly from npm and github https://github.com/jsdelivr/jsdelivr#usage

Example https://cdn.jsdelivr.net/npm/jquery@3.1.1
Example directory listing https://cdn.jsdelivr.net/npm/jquery@3.1.1/
