### ISSUE TITLE
Question: is it possible to map esc key to btnCancel in dialog.confirm()?

### ISSUE THREAD

**Issue by velis74** [nakupanda/bootstrap3-dialog#337]
Currently, if I call confirm with `closable=true`, the callback will not be called at all if closable option was used. So I can't do any processing when the dialog was closed with Esc key press. Onhide event also doesn't seem to work.
The callback will only be called when any of the two buttons was pressed.

What I'd like it for callback to still be called even if esc was pressed, but maybe the `result` variable would be set to null?

Is there a solution that would notify me of dialog closing, whatever the reason?

**Comment by nakupanda** [comment]
You can map ESC key press to button cancel with this

````
BootstrapDialog.confirm({
  closable: true,
	btnCancelHotkey: 27,
  callback: function(result) {
  	alert(result);
  }
});
````
However this is still not possible to call callback function when the 'x' icon was clicked.

**Comment by velis74** [comment]
Thank you for your explanation. In the mean time I have also discovered that the dialog itself is already destroyed by the time callback is called, so I cannot get form data any more.
I have simply reverted to "standard" dialog.open() with buttons and mapping esc to the cancel button. That worked like a charm.
