### ISSUE TITLE
Mouse over buttons will create unnecessary black margins

### ISSUE THREAD

**Issue by thinkp4d** [nakupanda/bootstrap3-dialog#360]
See the attached screenshots:

![000715](https://user-images.githubusercontent.com/31846877/30268494-91691a5e-96ee-11e7-8959-f08f2a8e5ed1.png)

![000714](https://user-images.githubusercontent.com/31846877/30268600-edf68bb2-96ee-11e7-9583-afb355b8e843.png)

Mouse over the top edges of the buttons will cause black margins to show up and eventually can ruin the whole page display.

**Comment by nakupanda** [comment]
Hi,

Can you create a jsfiddle to show us the problem? It's likely it's not any problem of bootstrap3-dialog.

**Comment by nakupanda** [comment]
Closing the issue as no feedback.
