### ISSUE TITLE
I have a problem opening a modal and filling the conten

### ISSUE THREAD

**Issue by mlozadad** [nakupanda/bootstrap3-dialog#361]
I have a problem opening a modal and filling the content

function instanceModal() {
    var dialogInstance = new BootstrapDialog({
        id: "idModal",
        title: $('<span>titulo</span>'),                      
        message: "idBodyModal",
        draggable: true,
        closable: false
    });

    dialogInstance.open();
}

//Return PartialView
$("#idBodyModal").load("@Url.Action("method", "controller")?par=1");

controller method is not executed,
I need to add settimeout

settimeout(function(){
//Return PartialView
$("#idBodyModal").load("@Url.Action("method", "controller")?par=1");
},150)

How can I solve this problem?
check the code and I did not find any settimeout

use
-MVC 4
-bootstrap-dialog.js 1.34.7
-Jquery 3.2.1
-Bootstrap 3.3.7

**Comment by nakupanda** [comment]
Sorry I can't help on this, maybe others who is familiar with MVC 4 can help you.
