### ISSUE TITLE
is there a bootstrap3-dialog callback demo?

### ISSUE THREAD

**Issue by 15838028035** [nakupanda/bootstrap3-dialog#362]
Hi,  is there a bootstrap3-dialog callback demo?  this is my code:
var url = ctx+"/jsp/user/upmUserSelectNew.jsp";
		var dialog = new BootstrapDialog({
		  	title:"选择人员",
		  cssClass :"speial-dialog",
		  size:BootstrapDialog.SIZE_WIDE,
		    message: $("<iframe  width=\"100%;\" height=\"800px\"; src="+url+"></iframe>"),
		  buttons: [ {
          label: '确定',
          action: function(dialogRef){
        	   parent.btn_select();
        	  var returnValue = dialogRef.getData("returnValue");
        	  alert("returnValue=" + returnValue);
             dialogRef.close();
        	  
          },
          callback: function(result){
        	  alert("result is:" + result);
          }
      }]
		});
		dialog.open();

  in the page upmUserSelectNew.jsp, i have some js function named btn_select(),
i want to set some value  by this bootstrap3-dialog,  what should i do ?  could you help me ?

**Comment by nakupanda** [comment]
You can access function inside iframe or reversely if the main page and the iframe are under the same domain. 

These might help:
https://stackoverflow.com/questions/1600488/calling-javascript-function-in-iframe
https://stackoverflow.com/questions/251420/invoking-javascript-code-in-an-iframe-from-the-parent-page
