### ISSUE TITLE
Pressing a space multiple times causes multiple modal boxes to appear

### ISSUE THREAD

**Issue by itcongaili** [nakupanda/bootstrap3-dialog#363]
Version: latest
![image](https://user-images.githubusercontent.com/11898652/32927033-5fc90df8-cb85-11e7-8091-2f250b20acd2.png)

**Comment by nakupanda** [comment]
Please create a jsfiddle so we can see the same page with same problems.

**Comment by itcongaili** [comment]
http://jsrun.net/jJiKp/edit
![qq 20171123182204](https://user-images.githubusercontent.com/11898652/33168438-dd6da8a4-d07b-11e7-967b-8a7939b51f1f.png)

**Comment by nakupanda** [comment]
@itcongaili Sorry replying so late. I guess the 'problem' was caused by the focus was on the button and when you press space it triggers a click event.

**Comment by glzcc** [comment]
thinks @nakupanda
