### ISSUE TITLE
How to use in ReactJS

### ISSUE THREAD

**Issue by sonhan** [nakupanda/bootstrap3-dialog#364]
I've got jQuery, Bootstrap included, and Bootstrap Modal is working. But cannot find a way to use this dialog. Have any of you successfully used this dialog with ReactJS?

`npm i jquery bootstrap bootstrap3-dialog`

```
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap3-dialog/dist/css/bootstrap-dialog.min.css';
import jQuery from 'jquery';
import BootstrapDialog from 'bootstrap3-dialog'; // I CANNOT IMPORT IT HERE
window.jQuery = jQuery;
require('bootstrap');

```

**Comment by sonhan** [comment]
Hi, I managed to make it work by using `var BootstrapDialog = require('bootstrap3-dialog');`

Then here are the guidelines for React, @nakupanda it you find it useful maybe you can include it in Readme

- Install
```
npm i jquery bootstrap bootstrap3-dialog
```

- Included in JSX file
```
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap3-dialog/dist/css/bootstrap-dialog.min.css';
import jQuery from 'jquery';

window.jQuery = jQuery;
var BootstrapDialog = require('bootstrap3-dialog');
```
- Use as normal
`BootstrapDialog.alert('I want banana!');`

**Comment by nakupanda** [comment]
@sonhan Thank you, will include this issue in Readme.

**Comment by nakupanda** [comment]
@sonhan Included this guideline in Readme. Thank you.
