### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by dandv** [nakupanda/bootstrap3-dialog#369]
Maybe I lack a sense of humor, or maybe there's a culture clash, but what in the world does "monkey-friendly" mean in this context?

**Comment by nakupanda** [comment]
See https://www.google.com.ph/search?q=code+monkey&source=lnms&tbm=isch

I guess now you understand somewhere in the world people would call 'programmer' as 'code-monkey'.

**Comment by nakupanda** [comment]
Especially in China, programmers are not only called 'Code-monkey' but also 'Code-farmer' (码农) or 'Bricks carrier' (搬砖工), of course these are all for fun.
