### ISSUE TITLE
Modal-backdrop on multiple opened dialogs

### ISSUE THREAD

**Issue by mreis1** [nakupanda/bootstrap3-dialog#5]
If we open a  second modal over an existant modal the backdrop doesn't overlay the previous opened modal. 

![captura de tela 2014-01-22 22 52 17](https://f.cloud.github.com/assets/1719667/1979923/f7aabe88-83b7-11e3-9e3a-c073012b31ea.png)

The problem seems to be related to how modals and modal-backdrops are being appended to html.

**Comment by cameron-martin** [comment]
The above solution causes problems when rendering popovers inside stacked modals, since the z-index of the top modal is higher than the popover.
